### ISSUE TITLE
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#10481]
## Issue - Bug

- **How serious is the bug?** P3
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`

Observed in 7.3.1 and through 7.4.2, but probably started before 7.3.1.

When running the pre-deploy script with the flag `--trace-deprecation` we get the following log

```
(node:69) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:193:11)
    at new Buffer (node:buffer:271:3)
    at alloc (/home/node/parabol/dist/preDeploy.js:176877:10)
    at 352847 (/home/node/parabol/dist/preDeploy.js:176865:54)
    at __webpack_require__ (/home/node/parabol/dist/preDeploy.js:237427:42)
    at 648204 (/home/node/parabol/dist/preDeploy.js:177080:37)
    at __webpack_require__ (/home/node/parabol/dist/preDeploy.js:237427:42)
    at 810816 (/home/node/parabol/dist/preDeploy.js:177530:17)
    at __webpack_require__ (/home/node/parabol/dist/preDeploy.js:237427:42)
    at 650897 (/home/node/parabol/dist/preDeploy.js:178348:18)
```

### Acceptance Criteria (optional)

The warning is not shown anymore

  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Please re-open if still applicable
