### ISSUE TITLE
`yarn build` fails with `ERR generating artifacts Error: Cannot find module './generated/getAtlassianAuthsByUserId'`

### ISSUE THREAD

**Issue by svenseeberg** [ParabolInc/parabol#10496]
## Bug

- **How serious is the bug?** P0 - P4
- **OS:** GNU/Linux Debian 12
- **Browser:** N/A
- **Node version:** v20.18.0 & v20.11.0
- **NPM version:** 10.8.2 & 10.2.4
- **Yarn version:** 1.22.22 & 1.22.5

On a newly cloned repo `yarn build` with v8.5.1 and down to the 7.x releases fails with:
```
$ node --max-old-space-size=8192 scripts/prod.js --non-interactive
🙏🙏🙏      Building Production Server      🙏🙏🙏
ERR generating artifacts Error: Cannot find module './generated/getAtlassianAuthsByUserId'
    at webpackMissingModule (webpack://parabol-action/./packages/server/postgres/queries/getAtlassianAuthsByUserId.ts?:2:103)
    at eval (webpack://parabol-action/./packages/server/postgres/queries/getAtlassianAuthsByUserId.ts?:2:215)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:241:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at eval (webpack://parabol-action/./packages/server/graphql/mutations/addAtlassianAuth.ts?:3:34)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:227:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at eval (webpack://parabol-action/./packages/server/graphql/rootMutation.ts?:2:25)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:220:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at eval (webpack://parabol-action/./packages/server/graphql/public/rootSchema.ts?:17:21)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:178:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at eval (webpack://parabol-action/./packages/server/graphql/private/rootSchema.ts?:3:19)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:143:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at eval (webpack://parabol-action/./packages/server/utils/updateGQLSchema.ts?:12:19)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:129:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:14195:41)
    at /opt/parabol/scripts/toolbox/updateSchema.js:14350:37
    at Object.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:14355:12)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._compile (/opt/parabol/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.newLoader [as .js] (/opt/parabol/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at updateGraphQLSchema (/opt/parabol/scripts/runSchemaUpdater.ts:27:10)
    at runSchemaUpdater (/opt/parabol/scripts/runSchemaUpdater.ts:32:10)
    at async generateGraphQLArtifacts (/opt/parabol/scripts/generateGraphQLArtifacts.js:10:3)
    at async prod (/opt/parabol/scripts/prod.js:24:5) {
  code: 'MODULE_NOT_FOUND'
}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The file `./packages/server/postgres/queries/getAtlassianAuthsByUserId.ts` contains
```javascript
import getPg from '../getPg'
import {getAtlassianAuthsByUserIdQuery} from generated/getAtlassianAuthsByUserId'
import {AtlassianAuth} from './getAtlassianAuthByUserIdTeamId'

const getAtlassianAuthsByUserId = async (userId: string) => {
  const res = await getAtlassianAuthsByUserIdQuery.run({userId}, getPg())
  if (!res || res.length === 0) return []
  return res.map((atlassianAuth) => ({
    ...atlassianAuth,
    jiraSearchQueries: atlassianAuth.jiraSearchQueries.map((jsq: any) => ({
      ...jsq,
      lastUsedAt: new Date(jsq.lastUsedAt)
    }))
  })) as AtlassianAuth[]
}

export default getAtlassianAuthsByUserId
```

AFAICT directory `./generated/` does not exist. There are some other dirs in other locations with this name. But the relative path would not point there.

**Comment by svenseeberg** [comment]
It seems  that this is a documentation issue. The [README](https://github.com/ParabolInc/parabol/blob/master/README.md?plain=1#L74) states that `yarn && yarn build && yarn predeploy && yarn start` should be executed for deployment. This is not correct. The steps seem to be `yarn && yarn pg:build && yarn build && yarn predeploy && yarn start`

**Comment by svenseeberg** [comment]
Also the migration step has to be included. Otherwise `yarn predeploy` fails with missing relations.
```
root@parabol /opt/parabol (git)-[tags/v8.5.1] # yarn pg:migrate up
yarn run v1.22.5
error Command "pg:migrate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1 root@parabol /opt/parabol (git)-[tags/v8.5.1] # yarn predeploy                                                                                                                                                :(
yarn run v1.22.5
$ node dist/preDeploy.js
🚀 Predeploy Started v8.5.1 sha:5129aa88b493c21163b2bd1699089731b8261e6c
🐘 Postgres Migration Started
🔩 Postgres Extension Checks Started
   pgvector: skipping check (POSTGRES_USE_PGVECTOR !== true)
🔩 Postgres Extension Checks Completed
  ✅ Migration: 2024-10-21T21:21:21.212Z_init
  ✅ Migration: 2024-10-24T22:26:35.877Z_integrationProviderUrls
  ✅ Migration: 2024-10-25T17:36:31.231Z_indexDiscussionTopicId
  ⛔️ Migration: 2024-10-28T15:49:33.276Z_add-feature-flags
🐘 Postgres Migration Failed
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

error: relation "FeatureFlag" does not exist
```
