### ISSUE TITLE
Users can't delete a dimension when creating a custom Sprint Poker meeting template

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#10545]
An Ent user demonstrated that they were unable to delete dimensions when on a call. Replicated bug [here](https://parabol.slack.com/archives/C03LL1JRFH8/p1733225989202319) 🔒 

## Issue - Bug

- **How serious is the bug?** P0 - P4
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`

### Acceptance Criteria (optional)

Users can:

- Do this
- Do that
- Cannot do that
  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by rafaelromcar-parabol** [comment]
We can see this bug in the logs. Yesterday it happened 16 times. Example [here](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20service%3Aparabol%20-kube_deployment%3Aparabol-embedder&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&event=AwAAAZO2oZR57iXmJgAAABhBWk8yb2FQR0FBQktZRTR2TVk5TWFRQUEAAAAkMDE5M2I3NGUtOGY4Mi00NjIwLWExNzktYjZjYmI1N2NmMmE2AABA-Q&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=pattern&from_ts=1733906284897&to_ts=1733992684897&live=true)

```
Error: Dimension not found
      at resolve (/home/node/parabol/dist/gqlExecutor.js:116537:51)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.MutationremovePokerTemplateDimensionResolver (/home/node/parabol/dist/gqlExecutor.js:144354:22)
```

**Comment by jordanh** [comment]
May be related: #9989

**Comment by Dschoordsch** [comment]
I cannot reproduce #9989, but this one. It also causes #11708 when after trying to delete going back, so I'll fix this one to see if it might resolve #9989.
