### ISSUE TITLE
Syntax error at or near "where" at updateTask

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#10591]
## Issue - Bug

- **How serious is the bug?** P2?
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`

```
error: syntax error at or near "where"
      at /home/node/parabol/dist/node_modules/pg/lib/index.js:2749:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresConnection.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1440351:28)
      at async /home/node/parabol/dist/gqlExecutor.js:1454834:28
      at async DefaultConnectionProvider.provideConnection (/home/node/parabol/dist/gqlExecutor.js:1440904:20)
      at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1454833:16)
      at async UpdateQueryBuilder.execute (/home/node/parabol/dist/gqlExecutor.js:1452925:24)
      at async UpdateQueryBuilder.executeTakeFirst (/home/node/parabol/dist/gqlExecutor.js:1452944:26)
      at async resolve (/home/node/parabol/dist/gqlExecutor.js:120711:23)
      at async Object.MutationupdateTaskResolver (/home/node/parabol/dist/gqlExecutor.js:144354:22)
      at PostgresConnection.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1440371:69)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /home/node/parabol/dist/gqlExecutor.js:1454834:28
      at async DefaultConnectionProvider.provideConnection (/home/node/parabol/dist/gqlExecutor.js:1440904:20)
      at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1454833:16)
      at async UpdateQueryBuilder.execute (/home/node/parabol/dist/gqlExecutor.js:1452925:24)
      at async UpdateQueryBuilder.executeTakeFirst (/home/node/parabol/dist/gqlExecutor.js:1452944:26)
      at async resolve (/home/node/parabol/dist/gqlExecutor.js:120711:23)
      at async Object.MutationupdateTaskResolver (/home/node/parabol/dist/gqlExecutor.js:144354:22) {
    locations: [ [Object] ],
    path: [ 'updateTask' ]
  }
```

[Example](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20service%3Aparabol%20-kube_deployment%3Aparabol-embedder&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&event=AwAAAZO1qzfZzCADmQAAABhBWk8xcXp0WEFBQWw0cVY0LUJrc3VBQUEAAAAkMDE5M2I2NzItZDcyNS00NzhjLTg5NTUtYTU4M2ZiNGEyMGQyAAA6JA&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=pattern&from_ts=1733906284897&to_ts=1733992684897&live=true)

### Acceptance Criteria (optional)

Users can:

- Do this
- Do that
- Cannot do that
  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
@rafaelromcar-parabol is this still occurring? I can't find any instances in Sentry

**Comment by rafaelromcar-parabol** [comment]
Can't find it neither! I would say resolved! Closing it now
