### ISSUE TITLE
Insert or update on table "Notification" violates foreign key constraint "fk_userId" at upsertTeamPromptResponse

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#10590]
## Issue - Bug

- **How serious is the bug?** P2?
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- Parabol v8.11.0

```
error: insert or update on table "Notification" violates foreign key constraint "fk_userId"
      at /home/node/parabol/dist/node_modules/pg/lib/index.js:2749:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresConnection.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1440351:28)
      at async /home/node/parabol/dist/gqlExecutor.js:1454834:28
      at async DefaultConnectionProvider.provideConnection (/home/node/parabol/dist/gqlExecutor.js:1440904:20)
      at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1454833:16)
      at async InsertQueryBuilder.execute (/home/node/parabol/dist/gqlExecutor.js:1450836:24)
      at async createTeamPromptMentionNotifications (/home/node/parabol/dist/gqlExecutor.js:128314:3)
      at async upsertTeamPromptResponse (/home/node/parabol/dist/gqlExecutor.js:132918:25)
      at async Object.upsertTeamPromptResponse (/home/node/parabol/dist/gqlExecutor.js:102418:14)
      at PostgresConnection.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1440371:69)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /home/node/parabol/dist/gqlExecutor.js:1454834:28
      at async DefaultConnectionProvider.provideConnection (/home/node/parabol/dist/gqlExecutor.js:1440904:20)
      at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/gqlExecutor.js:1454833:16)
      at async InsertQueryBuilder.execute (/home/node/parabol/dist/gqlExecutor.js:1450836:24)
      at async createTeamPromptMentionNotifications (/home/node/parabol/dist/gqlExecutor.js:128314:3)
      at async upsertTeamPromptResponse (/home/node/parabol/dist/gqlExecutor.js:132918:25)
      at async Object.upsertTeamPromptResponse (/home/node/parabol/dist/gqlExecutor.js:102418:14)
      at async Object.MutationupsertTeamPromptResponseResolver (/home/node/parabol/dist/gqlExecutor.js:144354:22) {
    locations: [ [Object] ],
    path: [ 'upsertTeamPromptResponse' ]
  }
```

[Pattern](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20service%3Aparabol%20-kube_deployment%3Aparabol-embedder&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=pattern&from_ts=1733906284897&to_ts=1733992684897&live=true) and [example](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20service%3Aparabol%20-kube_deployment%3Aparabol-embedder&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&event=AwAAAZO5U3X9S0Nt0gAAABhBWk81VTMxWEFBQ0V4eEVsRU5LSU1nQUIAAAAkMDE5M2I5NWEtNTc0OC00ZGJlLWFhNzMtZDMyYmI1NThkMzAzAAADvg&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=pattern&from_ts=1733906284897&to_ts=1733992684897&live=true)

### Acceptance Criteria (optional)

Users can:

- Do this
- Do that
- Cannot do that
  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
this happens for meetings that were created during about a 24-hour window when at-mentions in tiptap stored the teammemberId instead of the userId. I'll have to dig into who is causing this error. if it's just 1 team that keeps re-using the same meeting, i'm inclined to just let it be.

**Comment by Dschoordsch** [comment]
I cannot find any occurrences in Datadog or Sentry.
