### ISSUE TITLE
Error: invariant(...): Second argument must be a string.

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3129]
https://sentry.io/organizations/parabol/issues/1141632532/?referrer=github_plugin

```
Error: invariant(...): Second argument must be a string.
  at validateFormat (/home/circleci/action/node_modules/relay-runtime/node_modules/fbjs/lib/invariant.js:13:1)
  at invariant (/home/circleci/action/node_modules/relay-runtime/node_modules/fbjs/lib/invariant.js:31:1)
  at create (/home/circleci/action/node_modules/relay-runtime/lib/RelayRecordSourceMutator.js:210:269)
  at create (/home/circleci/action/node_modules/relay-runtime/lib/RelayRecordSourceProxy.js:95:1)
  at Object (../client/utils/relay/createProxyRecord.ts:28:27)
...
(11 additional frame(s) were not displayed)
```

AC
   - Root cause determined and new issue opened or bug fixed

EE
  - 12 points

**Comment by jordanh** [comment]
Scrubbed, iceboxing
