### ISSUE TITLE
17 Errors on Installation

### ISSUE THREAD

**Issue by downright-ux** [ParabolInc/parabol#3481]
I've done a pre-installation of Rethinkdb and tried using the .env file to get things started. But seem to run into the following error when doing "yarn quickstart".

```
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@~3.7.6"
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@^4.0.0-rc.12"
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested version "immutable@^4.0.0-rc.9"
[3/5] Fetching packages...
warning webpack-hot-client@4.1.2: Invalid bin field for "webpack-hot-client".
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @mattkrick/graphql-trebuchet-client@1.0.0" has incorrect peer dependency "@mattkrick/trebuchet-client@^0.3.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > draft-js@0.10.5" has unmet peer dependency "react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > draft-js@0.10.5" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @storybook/react@5.2.8" has unmet peer dependency "@babel/core@^7.0.1".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @storybook/react@5.2.8" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > eslint-plugin-prettier@3.1.1" has unmet peer dependency "prettier@>= 1.13.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > graphql-typed@0.4.1" has unmet peer dependency "@types/graphql@^14.0.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > graphql-relay@0.5.5" has incorrect peer dependency "graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > samlify@2.6.2" has unmet peer dependency "@authenio/samlify-libxml-xsd@^1.0.1".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > samlify@2.6.2" has unmet peer dependency "@authenio/samlify-validate-with-xmllint@^1.0.1".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > samlify@2.6.2" has unmet peer dependency "@authenio/samlify-xsd-schema-validator@^1.0.2".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-server > @mattkrick/graphql-trebuchet-client@0.2.0" has incorrect peer dependency "@mattkrick/trebuchet-client@^0.3.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @storybook/react > @babel/plugin-transform-react-constant-elements@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @storybook/react > @storybook/core@5.2.8" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "workspace-aggregator-a09c67e0-9d3f-4feb-8680-9952001e2d40 > parabol-client > @storybook/react > babel-plugin-named-asset-import@0.3.4" has unmet peer dependency "@babel/core@^7.1.0".
[5/5] Building fresh packages...
Done in 108.11s.
root@stg-retro:~/action/packages/server# yarn quickstart
yarn run v1.21.1
$ yarn db:migrate && yarn bs
$ yarn db:migrate-up-all
$ node database/migrate.babel.js up --all
Migrating DB actionDevelopment
[migrate-rethinkdb]  ↑  up  ↑  20160715095300 initialize
[migrate-rethinkdb]  ↑  up  ↑  20160722161700 meeting
[migrate-rethinkdb]  ↑  up  ↑  20160726160100 mockTeam
[migrate-rethinkdb]  ↑  up  ↑  20160906105600 add-agenda-ids
[migrate-rethinkdb]  ↑  up  ↑  20160923154400 project-archive
[migrate-rethinkdb]  ↑  up  ↑  20161013161900 project-history
Removing file /root/action/packages/server/rethinkdb_data/4a5c046c-cfd8-4490-8c53-269d22e4cbd4
[migrate-rethinkdb]  ↑  up  ↑  20161105214300 invitation
[migrate-rethinkdb]  ↑  up  ↑  20161114214000 allFacilitators
[migrate-rethinkdb]  ↑  up  ↑  20161121091100 addTmsOnMock
[migrate-rethinkdb]  ↑  up  ↑  20161125141100 addOrgs
NODE_ENV is testing. Removing, not migrating prior users.
[migrate-rethinkdb]  ↑  up  ↑  20170112135700 addInvoice
[migrate-rethinkdb]  ↑  up  ↑  20170202190500 addOrgApprovals
Removing file /root/action/packages/server/rethinkdb_data/db842ff0-d2af-444c-9564-809bde7c8ed2
[migrate-rethinkdb]  ↑  up  ↑  20170228132400 cleanupProjectIndices
[migrate-rethinkdb]  ↑  up  ↑  20170316073600 segmentIdentify
[migrate-rethinkdb]  ↑  up  ↑  20170330174100 addTeamIsArchived
[migrate-rethinkdb]  ↑  up  ↑  20170418145600 checkInGreetingObject
[migrate-rethinkdb]  ↑  up  ↑  20170502190200 addTags
Removing file /root/action/packages/server/rethinkdb_data/d489ffbb-e9e0-44ec-9082-1ae77f91624c
[migrate-rethinkdb]  ↑  up  ↑  20170515134300 fixTaggedContent
[migrate-rethinkdb]  ↑  up  ↑  20170516165400 backfillInvoices
NODE_ENV is testing or devving. Not backfilling invoices
[migrate-rethinkdb]  ↑  up  ↑  20170522164500 markdownToHTML
[migrate-rethinkdb]  ↑  up  ↑  20170628152000 addSlack
[migrate-rethinkdb]  ↑  up  ↑  20170714185200 addGitHub
[migrate-rethinkdb]  ↑  up  ↑  20170714185201 removeEmptyContent
[migrate-rethinkdb]  ↑  up  ↑  20170810164300 addProjectIntegrationId
[migrate-rethinkdb]  ↑  up  ↑  20170821152300 providerTeamIdsToTeamIdjs
[migrate-rethinkdb]  ↑  up  ↑  20170824163600 removeBadTeamMembers
[migrate-rethinkdb]  ↑  up  ↑  20170831142900 addUserEmailIndex
[migrate-rethinkdb]  ↑  up  ↑  20170906195000 removeNotificationVarList
[migrate-rethinkdb]  ↑  up  ↑  20170918163900 keepOrgApprovals
[migrate-rethinkdb]  ↑  up  ↑  20170921170700 fixInvitationExpiry
[migrate-rethinkdb]  ↑  up  ↑  20170926142800 freemium
[migrate-rethinkdb]  ↑  up  ↑  20171013142900 changeProjectIndex
[migrate-rethinkdb]  ↑  up  ↑  20171023195700 checkinQuestion
[migrate-rethinkdb]  ↑  up  ↑  20171026160540 removeBillingFromPersonalTeams
[migrate-rethinkdb]  ↑  up  ↑  20171115161524 fixRemovedTeamMember
[migrate-rethinkdb]  ↑  up  ↑  20171214122751 fixTeamTier
[migrate-rethinkdb]  ↑  up  ↑  20180117153603 softTeamMembers
[migrate-rethinkdb]  ↑  up  ↑  20180206135107 renameProjectToTask
[migrate-rethinkdb]  ↑  up  ↑  20180212124328 retro
[migrate-rethinkdb]  ↑  up  ↑  20180226074116 meetingSettings
[migrate-rethinkdb]  ↑  up  ↑  20180301081900 addOrgTierIndex
[migrate-rethinkdb]  ↑  up  ↑  20180305191107 customPhaseItems
[migrate-rethinkdb]  ↑  up  ↑  20180319122615 retroReflection
Removing file /root/action/packages/server/rethinkdb_data/dbef9aa1-003e-4eeb-95a8-8ed212e3e23e
Removing file /root/action/packages/server/rethinkdb_data/899ba2bf-ab3b-491d-804e-736b67a3312b
[migrate-rethinkdb]  ↑  up  ↑  20180320152455 voteSettings
[migrate-rethinkdb]  ↑  up  ↑  20180320200910 fix-retroReflection
[migrate-rethinkdb]  ↑  up  ↑  20180413152455 voteSettingsV2
[migrate-rethinkdb]  ↑  up  ↑  20180509162156 addFreeRetros
[migrate-rethinkdb]  ↑  up  ↑  20180904093953 addRetroTemplates
[migrate-rethinkdb]  ↑  up  ↑  20181212100647 invitationsv2
[migrate-rethinkdb]  ↑  up  ↑  20181220152050 newOrgUser
[migrate-rethinkdb]  ↑  up  ↑  20181221095933 addTimeline
[migrate-rethinkdb]  ↑  up  ↑  20181221124242 newFeatures
[migrate-rethinkdb]  ↑  up  ↑  20190305202636 removeLegacyInvite
Removing file /root/action/packages/server/rethinkdb_data/fbfe3ddf-22c8-4340-b8f7-c275dd937135
Removing file /root/action/packages/server/rethinkdb_data/f2306450-80e9-4664-a099-b1d7521a2223
[migrate-rethinkdb]  ↑  up  ↑  20190325150049 jira
[migrate-rethinkdb]  ↑  up  ↑  20190327165913 promptDescriptions
[migrate-rethinkdb]  ↑  up  ↑  20190415082651 integrationId
[migrate-rethinkdb]  ↑  up  ↑  20190425103700 removeGitHubRepos
Removing file /root/action/packages/server/rethinkdb_data/e07634f4-0b48-4c0c-b3c8-f4940634ac88
[migrate-rethinkdb]  ↑  up  ↑  20190509165854 legacyMeetingEvents
[migrate-rethinkdb]  ↑  up  ↑  20190516143948 queryMap
[migrate-rethinkdb]  ↑  up  ↑  20190521222803 slack
[migrate-rethinkdb]  ↑  up  ↑  20190528193756 removeOldMeeting
[migrate-rethinkdb]  ↑  up  ↑  20190612194707 scheduledJobs
[migrate-rethinkdb]  ↑  up  ↑  20190626105609 removeSoftTeamMembers
Removing file /root/action/packages/server/rethinkdb_data/0122eae7-3935-406f-a7cf-372fa9b7265b
[migrate-rethinkdb]  ↑  up  ↑  20190709134611 meetingFacilitatorIdx
[migrate-rethinkdb]  ↑  up  ↑  20190709193044 push-invitations
[migrate-rethinkdb]  ↑  up  ↑  20190809124635 plaintext-reflections
[migrate-rethinkdb]  ↑  up  ↑  20190818101532 renameBillingLeader
[migrate-rethinkdb]  ↑  up  ↑  20190904182024 saml
[migrate-rethinkdb]  ↑  up  ↑  20190909183628 null-cc
[migrate-rethinkdb]  ↑  up  ↑  20190912093945 remove-legacy-tables
Removing file /root/action/packages/server/rethinkdb_data/31185511-e919-473c-aee9-f5042acf14e5
Removing file /root/action/packages/server/rethinkdb_data/7ae8741b-5cea-43d1-bb59-333e95a7f581
[migrate-rethinkdb]  ↑  up  ↑  20191111140628 meetingNames
[migrate-rethinkdb]  ↑  up  ↑  20191120141523 byeAuth0
[migrate-rethinkdb]  ↑  up  ↑  20200103130450 shortMassInvite
[migrate-rethinkdb] Migration Successful
$ yarn build && yarn start
$ yarn build:relay && yarn build:client
$ yarn update-schema && yarn build:relay-unsafe
$ node utils/updateSchema.babel.js && yarn tsgen
Schema updated!
$ gql2ts ../../build/schema.json -e $(pwd)/../client/types/config.js -o ../client/types/graphql.ts && eslint --fix '../client/types/graphql.ts'
$ relay-compiler --customScalars.Email=string --customScalars.DateTime=string --customScalars.URL=string --noFutureProofEnums --src ../client --exclude '**/__generated__/**' --exclude '**/githubSchema.graphql' --schema ../../build/schema.json --extensions js ts tsx --artifactDirectory ../client/__generated__ --language typescript --client-schema ../client/clientSchema.graphql --persist-function graphql/persistFunction.js --persist-output graphql/queryMap.json --watchman false
$ webpack --config webpack/webpack.prod.config.js
ℹ ｢atl｣: Using typescript@3.7.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /root/action/packages/client/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
✖ ｢atl｣: Checking finished with 17 errors
Hash: e9e60510ba8534f6f024
Version: webpack 4.41.2
Time: 119200ms
Built at: 01/14/2020 2:23:35 AM
Entrypoint app [big] = vendors~app_f1f5ccda9935ae2dc48c.js vendors~app_e9e60510ba8534f6f024.js.map app_6eba23fba5016630551d.js app_e9e60510ba8534f6f024.js.map
   [2] /root/action/node_modules/react-router/esm/react-router.js + 1 modules 29.2 KiB {186} [built]
       |    2 modules
  [25] /root/action/node_modules/@emotion/core/dist/core.browser.esm.js + 5 modules 36.2 KiB {186} [built]
       |    6 modules
  [28] /root/action/node_modules/history/esm/history.js + 2 modules 30.6 KiB {186} [built]
       |    3 modules
  [56] (webpack)/buildin/global.js 472 bytes {186} [built]
 [105] ../client/utils/constants.ts 4.06 KiB {175} [built]
 [155] ../client/components/LoadingComponent/LoadingComponent.tsx + 1 modules 9.71 KiB {175} [built]
       |    2 modules
 [218] ../client/Atmosphere.ts 10.2 KiB {175} [built]
 [263] multi ../client/client.tsx 28 bytes {175} [built]
 [336] ../client/cdnFallback.js 259 bytes {175} [built]
 [409] ../client/scrollIntoViewIfNeeded.js 1.58 KiB {175} [built]
 [410] ../client/client.tsx + 12 modules 34.4 KiB {175} [built]
       | ../client/client.tsx 3.41 KiB [built]
       | ../client/Root.tsx 381 bytes [built]
       | ../client/styles/theme/globalStyles.ts 3.68 KiB [built]
       | ../client/hooks/useTrebuchetEvents.ts 3.17 KiB [built]
       | ../client/hooks/useServiceWorkerUpdater.ts 1.25 KiB [built]
       | ../client/styles/theme/fontLoader.ts 3.31 KiB [built]
       | ../client/mutations/ResetPasswordMutation.ts 927 bytes [built]
       |     + 6 hidden modules
 [415] ../client/modules/demo/LocalAtmosphere.ts + 19 modules 82.2 KiB {103} [built]
       | ../client/modules/demo/LocalAtmosphere.ts 2.5 KiB [built]
       | ../client/modules/demo/ClientGraphQLServer.ts 43.8 KiB [built]
       | ../client/modules/demo/handleCompletedDemoStage.ts 3.83 KiB [built]
       | ../client/utils/autogroup/groupReflections.ts 3.48 KiB [built]
       | ../client/utils/autogroup/getGroupSmartTitle.ts 946 bytes [built]
       | ../client/utils/sleep.ts 95 bytes [built]
       | ../client/utils/startStage_.js 172 bytes [built]
       | ../client/utils/unlockAllStagesForPhase.ts 469 bytes [built]
       | ../client/utils/unlockNextStages.js 1.34 KiB [built]
       | ../client/modules/demo/initBotScript.ts 11.9 KiB [built]
       | ../client/modules/demo/entityLookup.ts 1.75 KiB [built]
       | ../client/modules/demo/getDemoEntities.ts 538 bytes [built]
       | ../client/validation/normalizeRawDraftJS.ts 1.94 KiB [built]
       | ../client/utils/makeDiscussionStage.ts 401 bytes [built]
       | ../client/utils/makeGroupsToStages.ts 232 bytes [built]
       |     + 5 hidden modules
[2033] ../client/components/TeamInvitationRoot.tsx + 10 modules 20.9 KiB {156} [built]
       |    11 modules
[2043] ../client/components/InvitationLinkRoot.tsx + 4 modules 5.25 KiB {98} [built]
       |    5 modules
[2048] ../client/components/DemoMeeting.tsx + 2 modules 2.6 KiB {83} [built]
       | ../client/hooks/useMetaTagContent.ts 385 bytes [built]
       |     + 2 hidden modules
    + 2061 hidden modules

WARNING in [at-loader] ./graphql/mutations/createReflection.ts:103:58 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/removeReflection.ts:63:58 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/voteForReflectionGroup.ts:116:9 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.discuss' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:28 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:61 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:26 
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:33 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:25:14 
    TS2339: Property 'skipWaiting' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:40:32 
    TS6133: 'url' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:27 
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:34 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:52:14 
    TS2339: Property 'clients' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:61:31 
    TS2304: Cannot find name 'FetchEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:90:6 
    TS2339: Property 'oninstall' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:91:6 
    TS2339: Property 'onactivate' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:6 
    TS2339: Property 'onfetch' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:20 
    TS2304: Cannot find name 'FetchEvent'.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  5f792fb1f9641a6967ba7b68bb63f1ee.png (420 KiB)
  42ab379a5986fceddf1fed82a692a837.png (408 KiB)
  vendors~ActionMeetingRoot~DashboardRoot~DemoMeeting~DemoSummary~LocalAtmosphere~MeetingRoot~NewMeeti~ec0ad6a3_cc4279ffb9ecc959a1e9.js (685 KiB)
  vendors~ActionMeeting~AgendaAndTasksRoot~DemoMeeting~MyDashboardTasksRoot~MyDashboardTimelineRoot~Re~6051cce9_e1fba9956f98ca43c358.js (329 KiB)
  ActionMeetingRoot~DashboardRoot~DemoMeeting~MeetingRoot~NewMeetingRoot_6fc71ce94bf482675c26.js (343 KiB)
  DemoMeeting_121a1dd9b44078e15400.js (278 KiB)
  MeetingRoot_b342711e0b61a2174e2c.js (265 KiB)
  vendors~GraphqlContainer_ba162f870f7aa1d13675.js (1.7 MiB)
  vendors~TeamArchiveRoot_9de536df79e5755aaf34.js (370 KiB)
  vendors~app_f1f5ccda9935ae2dc48c.js (1.07 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.26 MiB)
      vendors~app_f1f5ccda9935ae2dc48c.js
      app_6eba23fba5016630551d.js

Child InjectManifest:
    Entrypoint undefined = sw.js 0_b753174f05064eacc5c1.js.map
    [0] ../client/serviceWorker/sw.ts 3.01 KiB {0} [built]
Child html-webpack-plugin for "index.html":
    Entrypoint undefined = index.html
    [0] /root/action/node_modules/html-webpack-plugin/lib/loader.js!./template.html 1.94 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
$ cross-env NODE_ENV=production node server.babel.js
buffer.js:305
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:305:9)
    at Object.<anonymous> (/root/action/packages/server/utils/getVerifiedAuthToken.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (/root/action/node_modules/pirates/lib/index.js:99:24)
    at Module._compile (/root/action/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at newLoader (/root/action/node_modules/pirates/lib/index.js:104:7)
    at newLoader (/root/action/node_modules/pirates/lib/index.js:104:7)
    at Object.newLoader [as .ts] (/root/action/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/action/packages/server/utils/getReqAuth.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (/root/action/node_modules/pirates/lib/index.js:99:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The only thing I have enabled in .env
```
HOST=<my-host-name>
PORT=3000
PROTO=http
REDIS_URL=redis://localhost:6379
RETHINKDB_URL=rethinkdb://localhost:28015/actionDevelopment
RETHINKDB_SSL=false
```

**Comment by mattkrick** [comment]
hey @downright-ux sorry for that bug, we're in the middle of getting rid of AUTH0 but haven't finished renaming all the env vars, so you'll need to add 1 more value to your env:
`AUTH0_CLIENT_SECRET="foobar"`

that should do it

**Comment by downright-ux** [comment]
Okay @mattkrick thanks for getting back so fast. I'll give that a try

**Comment by downright-ux** [comment]
@markusjwetzel looks like i got the server up and running now. 
 But throws a server error when trying to create an account.
Is there any logs or information I can help with debugging issue.

**Comment by jordanh** [comment]
@downright-ux just scrubbing some issues today and came across this.

Have you tried `yarn postdeploy`?

**Comment by jordanh** [comment]
Closing from inactivity
