### ISSUE TITLE
NS_ERROR_FAILURE: No error message

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3693]
https://sentry.io/organizations/parabol/issues/1570299265/?referrer=github_plugin

```
NS_ERROR_FAILURE: No error message
  at addFocusToSelection (/home/circleci/action/node_modules/draft-js/lib/setDraftEditorSelection.js:184:17)
  at 1084/</t.exports (/home/circleci/action/node_modules/draft-js/lib/setDraftEditorSelection.js:118:5)
  at this (/home/circleci/action/node_modules/draft-js/lib/DraftEditorLeaf.react.js:84:112)
  at componentDidUpdate (/home/circleci/action/node_modules/draft-js/lib/DraftEditorLeaf.react.js:107:5)
  at b (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:251:463)
...
(17 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
stumped on this, hoping some user feedback will help
