### ISSUE TITLE
TypeError: Cannot destructure property 'timeline' of 'a' as it is null.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3695]
https://sentry.io/organizations/parabol/issues/1578838164/?referrer=github_plugin

```
TypeError: Cannot destructure property 'timeline' of 'a' as it is null.
  at c (../client/components/TimelineFeedList.tsx:15:10)
  at Ih (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:154:98)
  at gk (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:259:456)
  at fk (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:230:22)
  at Zj (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:229:362)
...
(7 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
stumped on this, hoping some user feedback will help
