### ISSUE TITLE
Timeline events for meetings that ended early

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3778]
I’ve seen recently that meetings that were ended early are being included on the timeline. One of the bugs I’ve found is that clicking ‘review a summary’ on the retro event card fails silently for the user. The error logged to the console is:

```
SEND TO SENTRY GraphQLError: Cannot return null for non-nullable field RetrospectiveMeeting.(reflectionGroups,reflectionGroups).
    at RetrospectiveMeetingreflectionGroupsMapItemHandler (eval at compileQuery (/Users/terryacker/code/parabolinc/parabol/node_modules/graphql-jit/src/execution.ts:237:9), <anonymous>:473:73)
    at RetrospectiveMeetingreflectionGroupsMapHandler (eval at compileQuery (/Users/terryacker/code/parabolinc/parabol/node_modules/graphql-jit/src/execution.ts:237:9), <anonymous>:751:8)
    at Object.safeMap (/Users/terryacker/code/parabolinc/parabol/node_modules/graphql-jit/src/execution.ts:1045:5)
    at reflectionGroupsRetrospectiveMeetingreflectionGroupsResolverHandler (eval at compileQuery (/Users/terryacker/code/parabolinc/parabol/node_modules/graphql-jit/src/execution.ts:237:9), <anonymous>:771:13)
    at __parent.newMeeting.__value.then.__context.nullErrors.push.__context.GraphQLError.line (eval at compileQuery (/Users/terryacker/code/parabolinc/parabol/node_modules/graphql-jit/src/execution.ts:237:9), <anonymous>:3010:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) undefined
```

### AC
- Decided on what meetings make it to the timeline e.g. we don’t show timeline events for retro meetings that didn’t make it to the discuss phase
- Links work on meeting event cards (e.g. ‘review a summary’) for whatever meetings make it to the timeline
### EE
- 10.5 pts

**Comment by jordanh** [comment]
Related to #3956, retest when that issue hits production
