### ISSUE TITLE
🏁  Release v5.12.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3997]
## The basics
- [x] Smoke tested the [Demo](https://action-staging.parabol.co/retrospective-demo), unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works (Team > Invite Button > Invite Link, visit URL in an incognito window)
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notifications (use `#t_product_actiontime`)
- [x] Added GitHub, verified issue created (use `ParabolInc/publictestrepo`)
- [x] Added Jira, verified issue created (use `parabol-2`)
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro (Credit card number: `4242 4242 4242 4242`, expiration date: any month in the future, CVC: `123`)
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
### Added

- Added thread comments to the CSV export #3948
- Added automated screenshots for Parabol demo #3907
- Added `enableSAMLForDomain` mutation for private schema #3986
- Customized prettier for the Typescript file generated by [gql2ts](https://github.com/amount/gql2ts) #3995

### Changed

- Optimized metrics query to run faster #3978
- Set up config to enable client code debugging in VS Code #3985
- Deprecated `meetingSettingsByTeamId` in favor of `meetingSettingsByType` #3973

### Fixed

- Fixed source maps to enable debugging with breakpoints in VS Code #3982
- Fixed a typo for `utm_source` in meeting summary URL parameters #3977
- Fixed a typo in `DemoCreateAccountButton` #3972
- Fixed duplicate agenda item pins #3996

**Comment by ackernaut** [comment]
### Borked new meeting view
- Navigate via Start New Meeting and you’ll find the fatal error screen and errors in the browser’s console, a snippet:
```
instrument.js:110 RelayNetwork: No data returned for operation `NewMeetingRootQuery`, got error(s):
Server error

See the error `source` property for more information.
    at r (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:146540)
    at Object.create (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:146635)
    at e._handleNext (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:353214)
    at https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:352979
    at e._schedule (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:352680)
    at e._next (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:352955)
    at Object.next (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:351673)
    at Object.next (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:73136)
    at r.fetch (https://action-files.parabol.co/staging/build/v5.11.1/vendors~app_df1c3e1fa9c255ce3e1a.js:1:78216)```

**Comment by ackernaut** [comment]
### I see the join snackbar when I start the meeting

- Start a meeting
- See the join snackbar `You just started Retro ## Join Now`

It should only show for other team members who are on a dashboard view.
