### ISSUE TITLE
Fix integration test failure "Test Discuss page Demo can navigate back to a previous item"

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4248]
See [CircleCI test failure](https://app.circleci.com/pipelines/github/ParabolInc/parabol/973/workflows/860a5808-7327-4915-b6fd-25790a0c3447/jobs/9868):

Screenshot is [here](https://9868-48384473-gh.circle-artifacts.com/0/cypress/screenshots/demo_discuss.ts/Test%20Discuss%20page%20Demo%20--%20can%20navigate%20back%20to%20a%20previous%20item%20%28failed%29.png). Video is [here](https://9868-48384473-gh.circle-artifacts.com/0/cypress/videos/demo_discuss.ts.mp4).

**Test Discuss page Demo can navigate back to a previous item - can navigate back to a previous item**

```
CypressError: Timed out retrying: `cy.click()` failed because this element is not visible:

`<div data-cy="discuss-item-1" data-rbd-draggable-context-id="0" data-rbd-draggable-id="LhlkvmFhj" tabindex="0" data-rbd-drag-handle-draggable-id="LhlkvmFhj" data-rbd-drag-handle-context-id="0" aria-labelledby="rbd-lift-instruction-0" draggable="false" class="css-0">...</div>`

This element `<div.css-0>` is not visible because its ancestor has `position: fixed` CSS property and it is overflowed by other elements. How about scrolling to the element with `cy.scrollIntoView()`?

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
    at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:146259:16)
    at cypressErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:146268:10)
    at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:146231:11)
    at Object.ensureVisibility (http://localhost:3000/__cypress/runner/cypress_runner.js:137237:24)
    at runAllChecks (http://localhost:3000/__cypress/runner/cypress_runner.js:127499:14)
    at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:127542:16)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
    at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:6333:29)
    at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:140318:21)
    at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:140353:12)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:139897:16
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:6994:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:7051:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:7096:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:7176:18)
```

### Acceptance Criteria

*   **Test Discuss page Demo can navigate back to a previous item - can navigate back to a previous item** test passed.

Estimation: 2 hours

**Comment by tiffanyhan** [comment]
late to this one. should this issue be closed? i tried running tests locally today and all passed.

<img width="810" alt="Screen Shot 2020-10-23 at 3 32 51 PM" src="https://user-images.githubusercontent.com/11562889/97059344-083bde00-1545-11eb-9888-10e7d0305eff.png">

**Comment by tianrunhe** [comment]
Yup it's fixed by Matt.
