### ISSUE TITLE
Fix integration test failure "Test archived task checkbox in Task View"

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4249]
See [CircleCI test failure](https://app.circleci.com/pipelines/github/ParabolInc/parabol/973/workflows/860a5808-7327-4915-b6fd-25790a0c3447/jobs/9868):

Screenshot is [here](https://9868-48384473-gh.circle-artifacts.com/0/cypress/screenshots/archivedTasks.ts/archivedTasks%20--%20Test%20archived%20task%20checkbox%20in%20Task%20View%20%28failed%29.png). Video is [here](https://9868-48384473-gh.circle-artifacts.com/0/cypress/videos/archivedTasks.ts.mp4).

**archivedTasks Test archived task checkbox in Task View - Test archived task checkbox in Task View**

```
AssertionError: Timed out retrying: expected '<body>' to contain 'There are zero archived tasks'
    at applyChainer (http://localhost:3000/__cypress/runner/cypress_runner.js:131730:32)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:131771:16
    at arrayReduce (http://localhost:3000/__cypress/runner/cypress_runner.js:18403:21)
    at Function.reduce (http://localhost:3000/__cypress/runner/cypress_runner.js:27401:14)
    at applyChainers (http://localhost:3000/__cypress/runner/cypress_runner.js:131761:18)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
    at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:6333:29)
    at Context.shouldFn (http://localhost:3000/__cypress/runner/cypress_runner.js:131775:23)
    at Context.should (http://localhost:3000/__cypress/runner/cypress_runner.js:131790:23)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:127819:39
    at assertions (http://localhost:3000/__cypress/runner/cypress_runner.js:128079:14)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
    at Object.gotValue (http://localhost:3000/__cypress/runner/cypress_runner.js:8203:18)
    at Object.gotAccum (http://localhost:3000/__cypress/runner/cypress_runner.js:8190:25)
    at Object.tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:6994:31)
```

### Acceptance Criteria

*   **archivedTasks Test archived task checkbox in Task View - Test archived task checkbox in Task View** test passed.

Estimation: 2 hours

**Comment by jordanh** [comment]
Iceboxing
