### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by WaelSan** [ParabolInc/parabol#4285]
- **OS:** Linux  ubuntu 18.04 server
- **Node version:** v15.0.1 ( I tried also v13.6.0 and v14.10.0)
- **NPM version:** 6.14.8

When I start yarn, I get this error:
(I'm also getting this error with the docker image)
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:258:15)
    at Function.from (node:buffer:317:9)
    at Object.223 (/root/parabol-master/dist/sfu.js:1:4103)
    at r (/root/parabol-master/dist/sfu.js:1:110)
    at Module.290 (/root/parabol-master/dist/sfu.js:1:14680)
    at r (/root/parabol-master/dist/sfu.js:1:110)
    at Object.288 (/root/parabol-master/dist/sfu.js:1:5012)
    at r (/root/parabol-master/dist/sfu.js:1:110)
    at /root/parabol-master/dist/sfu.js:1:960
    at Object.<anonymous> (/root/parabol-master/dist/sfu.js:1:971)
2020-10-24T20:33:15: PM2 log: App name:Media SFU Server id:2 disconnected
2020-10-24T20:33:15: PM2 log: App [Media SFU Server:2] exited with code [0] via signal [SIGINT]
2020-10-24T20:33:15: PM2 log: Script /root/parabol-master/dist/sfu.js had too many unstable restarts (16). Stopped. "errored"

```

**Comment by WaelSan** [comment]
resolved by using:
yarn: `v1.22.5`
node: `v14.10.0`
Removing unused variables from `.env` file
And running `yarn db:migrate`

**Comment by jghaanstra** [comment]
I have the same issue. I'm using the same setup within Docker that resolved it for @WaelSan and have also run `yarn db:migrate` within the app container. All has been to no avail, I keep getting this error. Anyone got an idea on how to solve this?

**Comment by WaelSan** [comment]
You need to verify the node,npm, and yarn version.
Edit also Dockerfile.prod, add these lines before yarn start:
```
npx browserslist@latest --update-db
yarn build
yarn db:migrate

```

**Comment by jghaanstra** [comment]
@WaelSan thank you but I still have been unable to solve this. I checked all version and added the above lines to no avail. Could you post your entire Dockerfile.prod here as reference?
