### ISSUE TITLE
TypeError: Object doesn't support property or method 'composedPath'

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4479]
https://sentry.io/organizations/parabol/issues/1638935078/?referrer=github_plugin

```
TypeError: Object doesn't support property or method 'composedPath'
  at z (./packages/client/utils/findDropZoneFromEvent.ts:14:3)
  at ref (./packages/client/hooks/useDraggableReflectionCard.tsx:261:5)
  at Anonymous function (./packages/client/hooks/useEventCallback.ts:14:12)
```

**Comment by jordanh** [comment]
## AC
- [ ] Triage
- [ ] Open new issue with root cause or fix

### EE: 6 hours

**Comment by jordanh** [comment]
Could no longer locate issue in Sentry
