### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4481]
https://sentry.io/organizations/parabol/issues/1874718788/?referrer=github_plugin

```
TypeError: Cannot read property 'indexOf' of null
  at r (/leadflows.js:7:1947)
  at XMLHttpRequest.t.onreadystatechange (/leadflows.js:7:2319)
```

**Comment by jordanh** [comment]
## AC
- [ ] Triage
- [ ] Open new issue with root cause or fix

### EE: 6 hours

**Comment by jordanh** [comment]
Watermark: 66 users affected

**Comment by jordanh** [comment]
No further incidents in Sentry, closing
