### ISSUE TITLE
TypeError: Cannot read property 'setLinkedRecord' of undefined

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4644]
https://sentry.io/organizations/parabol/issues/2198482325/?referrer=github_plugin

```
TypeError: Cannot read property 'setLinkedRecord' of undefined
  at setActiveTemplateInRelayStore (./packages/client/utils/relay/setActiveTemplate.ts:12:21)
  at handler (./packages/client/mutations/AddReflectTemplateMutation.ts:41:3)
  at updater (./packages/client/subscriptions/TeamSubscription.ts:132:9)
  at Set.forEach (<anonymous>)
  at updateIsEditing (./packages/client/components/ReflectionCard/ReflectionCard.tsx:72:5)
...
(29 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Watermark: 1 user affected

**Comment by jordanh** [comment]
No further incidents in Sentry. Closing
