### ISSUE TITLE
Team invitation request isn't sending

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4744]
I can reproduce this bug in development but not in production.

To reproduce:

- Open two browsers with two different users
- User A goes to the URL of User B's team / meeting
- The invitation request snackbar doesn't show up

When trying to join a team, a stack trace error says the `Argument "meetingId" of non-null type "ID!" must not be null`. When joining a meeting, it complains that the `teamId` is undefined.

**Comment by nickoferrall** [comment]
We've shipped but I'm unable to repro this bug on prod 🤔  It still exists locally for me. 

Will keep this issue open until either:

- Someone confirms that they don't get this error locally meaning something funky is happening on my device
- I've fixed the bug locally

I think the `pushInvitation` mutation is the culprit. `meetingId` is nullable which suggests that the error comes from elsewhere. However, the payload being returned from `pushInvitation` is `null` even though I can see that the mutation is sending the correct data.

**Comment by tianrunhe** [comment]
Invitation request snack bar shows up for me:

![2021-03-05 14 32 00](https://user-images.githubusercontent.com/1879975/110181052-cdce3180-7dbf-11eb-8aed-33c8672def77.gif)

However I did see the errors in console:
```
SEND TO SENTRY Error: No mutator id in setAppLocation.ts
    at eval (webpack-internal:///./packages/server/graphql/mutations/setAppLocation.ts:42:68)
    at Object.eval [as MutationsetAppLocationResolver] (webpack-internal:///./packages/server/graphql/rateLimit.ts:55:10)
    at Array.setAppLocationMutationsetAppLocationResolverMutation (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:140:39)
    at query (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:20:25)
    at Object.SetAppLocationMutation [as query] (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:135:33)
    at executeGraphQL (webpack-internal:///./packages/server/graphql/executeGraphQL.ts:75:40)
    at Redis.onMessage (webpack-internal:///./packages/gql-executor/gqlExecutor.ts:20:26)
    at Redis.emit (events.js:314:20)
    at Redis.EventEmitter.emit (domain.js:486:12)
    at DataHandler.handleSubscriberReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/Users/brucetian/Projects/parabol/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12) undefined
Trace: {
  error: '[{"message":"Argument \\"teamId\\" of non-null type \\"ID!\\" must not be null.","locations":[{"line":17,"column":16}],"path":["viewer","team"]}]'
}
    at executeGraphQL (webpack-internal:///./packages/server/graphql/executeGraphQL.ts:85:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Redis.onMessage (webpack-internal:///./packages/gql-executor/gqlExecutor.ts:20:20)
SEND TO SENTRY [Error: Argument "teamId" of non-null type "ID!" must not be null.] undefined
```

**Comment by tianrunhe** [comment]
Hmmmm... you think these [thousands of Sentry events](https://sentry.io/organizations/parabol/issues/2206626797/?project=107196&query=is%3Aunresolved&sort=freq&statsPeriod=14d) are related?

**Comment by tianrunhe** [comment]
I think the error `Argument \\"teamId\\" of non-null type \\"ID!\\" must not be null.` comes from `ViewerNotOnTeamRootQuery`:

<img width="2150" alt="Screen Shot 2021-03-05 at 3 41 11 PM" src="https://user-images.githubusercontent.com/1879975/110186244-792fb400-7dc9-11eb-8668-2fb7cc7cebe9.png">

**Comment by nickoferrall** [comment]
> Hmmmm... you think these thousands of Sentry events are related?

Nice find! It's good to hear that the snackbar shows up for you. It still works on prod but not dev for me. Keeping this issue open
