### ISSUE TITLE
Unable to read integrations in poker

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4775]
Affected 191 users in the past 12 days

https://sentry.io/organizations/parabol/issues/2253468575/?referrer=github_plugin

```
TypeError: Cannot read property 'atlassian' of undefined
  at fn (./packages/client/components/ScopePhaseAreaAddJira.tsx:48:83)
  at _optionalChain (./packages/client/components/ScopePhaseAreaAddJira.tsx:1:544)
  at c (./packages/client/components/ScopePhaseAreaAddJira.tsx:48:36)
...
(9 additional frame(s) were not displayed)
```

**Comment by nickoferrall** [comment]
Hey @mattkrick, this bug has affected quite a few users since the last release. I haven't been able to reproduce it yet but I've pushed a [small change](https://github.com/ParabolInc/parabol/commit/7e3d8b38be63bdf9a8b67514ed56d1400de52840) to master (accidentally..) that checks if integrations exist. 

Integrations is non nullable and I know that Relay has caused some bugs where a non-nullable field ends up being `null`, but the frequency of this bug suggests to me that it could be something else.
