### ISSUE TITLE
TypeError: Cannot read property 'getValue' of null

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4969]
https://sentry.io/organizations/parabol/issues/2164826451/?referrer=github_plugin

This affected 1 user 2 days ago (as of Fri May 14) at v6.10.1 . This affected another user 8 months ago at v5.31.3

```
TypeError: Cannot read property 'getValue' of null
  at removeReflectionMeetingUpdater (./packages/client/mutations/RemoveReflectionMutation.ts:62:43)
  at updater (./packages/client/mutations/RemoveReflectionMutation.ts:84:7)
  at Set.forEach (<anonymous>)
  at updateIsEditing (./packages/client/components/ReflectionCard/ReflectionCard.tsx:74:5)
  at c (./packages/client/components/ReflectionCard/ReflectionCard.tsx:85:18)
...
(29 additional frame(s) were not displayed)
```

### Acceptance criteria
- Triage and fix, or open a new issue with root cause to be fixed

### Estimated effort
- 4 hours

**Comment by jordanh** [comment]
No more instances in Sentry, closing
