### ISSUE TITLE
Cannot read property 'getLinkedRecords' of null

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5040]
Affected 6 users in the past 8 days. The updater is unable to grab `meeting`

https://sentry.io/organizations/parabol/issues/2442168174/?referrer=github_plugin

```
TypeError: Cannot read property 'getLinkedRecords' of null
  at resetMeetingToStageUpdater (./packages/client/mutations/ResetMeetingToStageMutation.ts:55:43)
  at updater (./packages/client/mutations/ResetMeetingToStageMutation.ts:75:7)
  at Set.forEach (<anonymous>)
  at updateLocalStage (./packages/client/utils/relay/updateLocalStage.ts:27:3)
  at gotoStageId (./packages/client/hooks/useGotoStageId.ts:59:7)
...
(25 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
No further instances in Sentry. Closing
