### ISSUE TITLE
Unable to sign-up / sign-in on dev server

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5047]
When trying to create a new user on the [dev server](https://action-dev-nyc1-01.parabol.co/create-account), a server error is displayed. 

After uploading the staging db to the dev server and updating the db name to `actionProduction`, the User table doesn't contain any records even though the staging db does. 

After manually creating a user with the dev server explorer, I still get the same server error message.

Here are the logs:
```
2021-06-14T19:40:58.955860657Z app[web.1]: SEND TO SENTRY Error: We do not have a jwt in getVerifiedAuthToken
2021-06-14T19:40:58.955890030Z app[web.1]:     at c (/app/dist/web.js:24:520729)
2021-06-14T19:40:58.955894877Z app[web.1]:     at p (/app/dist/web.js:24:520979)
2021-06-14T19:40:58.955900073Z app[web.1]:     at /app/dist/web.js:24:1013255
2021-06-14T19:40:58.955903648Z app[web.1]:     at /app/dist/web.js:24:521954
2021-06-14T19:40:58.955907334Z app[web.1]:     at topLevelDomainCallback (domain.js:147:15)
2021-06-14T19:40:58.955911194Z app[web.1]:     at callbackTrampoline (internal/async_hooks.js:132:14) undefined
2021-06-14T19:40:58.968123481Z app[web.1]: SEND TO SENTRY [Error] undefined
``` 

This issue blocks #4964 as we need to share the dev server with the Slack folks so that they can play with the staging app

**Comment by mattkrick** [comment]
fix should already be in prod here: https://github.com/ParabolInc/parabol/pull/5044/files

could you try making an organizationBackup from the production server? Maybe the staging server missed a fix
