### ISSUE TITLE
TypeError: Cannot destructure property 'userId' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5080]
Affecting 8 users in the last 2-4 weeks. First seen in 6.1.0

https://sentry.io/organizations/parabol/issues/2238907262/?referrer=github_plugin

```
TypeError: Cannot destructure property 'userId' of 'undefined' as it is undefined.
  at None (./packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx:29:61)
  at Array.findIndex (<anonymous>)
  at a (./packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx:29:49)
  at c (./packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx:29:23)
...
(12 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
No more instances in Sentry. Closing
