### ISSUE TITLE
Error on start project

### ISSUE THREAD

**Issue by gozar33** [ParabolInc/parabol#5302]
When I run `yarn` I got this error:

```
error D:\parabol\node_modules\mediasoup: Command failed.
Exit code: 1
Command: node npm-scripts.js postinstall
Arguments:
Directory: D:\parabol\node_modules\mediasoup
Output:
npm-scripts.js [INFO] running task "postinstall"
```

and when I run `yarn start` I got this error:
```
yarn run v1.22.11
$ pm2-runtime start pm2.config.js
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at Object.instanciate (D:\parabol\node_modules\pm2\lib\binaries\Runtime4Docker.js:66:47)
    at Command.<anonymous> (D:\parabol\node_modules\pm2\lib\binaries\Runtime4Docker.js:54:13)
    at Command.listener (D:\parabol\node_modules\pm2\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (D:\parabol\node_modules\pm2\node_modules\commander\index.js:651:12)
    at Command.parse (D:\parabol\node_modules\pm2\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\parabol\node_modules\pm2\lib\binaries\Runtime4Docker.js:190:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

- OS: Windows 
- Browser: Chrome 
- Node version:14.16.1
- NPM version: 6.14.12

I also migrated to  yarn 3 but got  error in get one of node module packages.

Estimated effort: more than few days

**Comment by mattkrick** [comment]
there's a yarn 3 now?! we're still on ~v1.22

We currently don't have a dev who uses windows so I can't help any further, but if you find the problem please drop us an update or a PR!

**Comment by gozar33** [comment]
> there's a yarn 3 now?! we're still on ~v1.22
> 
> We currently don't have a dev who uses windows so I can't help any further, but if you find the problem please drop us an update or a PR!

Thank's for answer. yes there is yarn v3 but it's not stable.
![Untitled](https://user-images.githubusercontent.com/76527180/130679209-2b035239-e09f-498e-a155-f7dfa5a91907.png)
