### ISSUE TITLE
payload can be null in ResetRetroMeetingToGroupStageMutation

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5383]
Affected 9 users in the past 16 days since v6.24.1

https://sentry.io/organizations/parabol/issues/2607259830/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'getLinkedRecords')
  at resetRetroMeetingToGroupStageUpdater (./packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts:52:43)
  at updater (./packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts:73:7)
  at Set.forEach (<anonymous>)
  at updateIsEditing (./packages/client/components/ReflectionCard/ReflectionCard.tsx:110:5)
  at g (./packages/client/components/ReflectionCard/ReflectionCard.tsx:121:18)
...
(15 additional frame(s) were not displayed)
```

**Comment by shapel** [comment]
@nickoferrall do you have a chance to review this?
