### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5410]
https://sentry.io/organizations/parabol/issues/2570733205/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

affects 4 users.

```
{
message: Cannot read property 'map' of null, 
name: TypeError, 
stack: 
TypeError: Cannot read property 'map' of null
    at https://action-files.parabol.co/production/build/v6.27.0/8589_7b43a13882ea12e08a91.js:1:14591
    at Object.useMemo (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:167140)
    at t.useMemo (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:298172)
    at o (https://action-files.parabol.co/production/build/v6.27.0/8589_7b43a13882ea12e08a91.js:1:14566)
    at https://action-files.parabol.co/production/build/v6.27.0/ScopePhase_d94e95ccf92341d337ec.js:8:24823
    at oa (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:161217)
    at Gs (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:213456)
    at Tl (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:200662)
    at Rl (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:200590)
    at xl (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:200453)
    at _l (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:197440)
    at https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:147112
    at t.unstable_runWithPriority (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:423316)
    at Bo (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:146889)
    at Ko (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:147057)
    at Wo (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:146992)
    at De (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:217976)
    at Yt (https://action-files.parabol.co/production/build/v6.27.0/app_a8d1277a18d5f10e63b6.js:40:12...
```

**Comment by jordanh** [comment]
No new instances. Closing
