### ISSUE TITLE
TypeError: Cannot destructure property 'name' of 's' as it is undefined.

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5678]
Affected 6 users in the last 30 days.

https://sentry.io/organizations/parabol/issues/2155601578/?referrer=github_plugin

```
TypeError: Cannot destructure property 'name' of 's' as it is undefined.
  at makeTemplateDescription (./packages/client/utils/makeTemplateDescription.ts:20:16)
  at c (./packages/client/modules/meeting/components/ReflectTemplateDetails.tsx:94:23)
...
(10 additional frame(s) were not displayed)
```

Estimated effort: 1 hour to triage. More if the root cause is already identified.

**Comment by jordanh** [comment]
Watermark: 55 events, 1 user affected last 30. Going to icebox
