### ISSUE TITLE
No data returned for TeamContainerQuery on Safari

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5731]
Affected 5 users in the past 15 hours. All incidents happened on Safari.

https://sentry.io/organizations/parabol/issues/2827071229/?referrer=github_plugin

```
RelayNetwork: No data returned for operation `TeamContainerQuery`, got error(s):
The request took too long

See the error `source` property for more information.
  at React (./packages/client/components/Action/Action.tsx:39:21)
  at None (./packages/client/components/PrivateRoutes.tsx:51:9)
  at forEach ([native code])
  at status (./packages/client/components/PrivateRoutes.tsx:48:150)
  at Route (./packages/client/components/SnackbarMessage.tsx:32:39)
...
(24 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Related? #5732

**Comment by jordanh** [comment]
Iceboxing
