### ISSUE TITLE
Request takes too long on Safari

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5732]
Affected 26 users in the past 2 months. All incidents happened on Safari. Sentry issue doesn't share particularly useful information, but I thought I'd document this anyway incase it's a helpful clue when investigating slow queries. 

https://sentry.io/organizations/parabol/issues/2696130536/?referrer=github_plugin

```
Error: The request took too long
  at dispatch (./node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLTrebuchetClient.js:44:32)
  at None (./node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLTrebuchetClient.js:9:18)
  at emit (./node_modules/react-dom/cjs/react-dom.production.min.js:143:427)
  at None (./node_modules/@mattkrick/trebuchet-client/lib/SocketTrebuchet.js:113:26)
```

**Comment by jordanh** [comment]
Elevating priority

**Comment by jordanh** [comment]
Iceboxing
