### ISSUE TITLE
Reflections don't show up in UI

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5762]
## Issue - Bug

https://www.loom.com/share/e864e49d06104c4bad2e4327fcb799a8

When testing retro meetings for v6.40.0-rc.1 on staging, when any user creates a reflection and submits it, it disappears in the UI. The reflection is successfully saved to db, so looks like a client side UI problem.

### Acceptance Criteria (optional)
Users can:
   - Create a reflection and see it in the reflect column
   - See reflections their teammates have created in the reflect column 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tiffanyhan** [comment]
**Story Points: 10**
  [See the discussion](https://action-staging.parabol.co/meet/9bbrxfUeis/estimate/4) in Sprint Poker #​​2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by BartoszJarocki** [comment]
We're getting an error when creating the reflection on the backend, it returns no data so there's nothing to show on the frontend 
```
TypeError: Cannot read properties of undefined (reading '_batch')
    at getCurrentBatch (/Users/bjarocki/Work/parabol/web-parabol/node_modules/dataloader/index.js:242:30)
    at load (/Users/bjarocki/Work/parabol/web-parabol/node_modules/dataloader/index.js:54:17)
    at Object.CreateReflectionPayloadreflectionGroupResolver (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:31075:20)
    at createReflectionMutationcreateReflectionResolverHandler (eval at compileQuery (/Users/bjarocki/Work/parabol/web-parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:1567:39)
    at __value.then.__context.errors.push.__context.GraphQLError.line (eval at compileQuery (/Users/bjarocki/Work/parabol/web-parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:1735:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Trace: {
  error: `{"data":{"createReflection":{"reflectionGroup":null,"unlockedStages":null}},"errors":[{"message":"Cannot read properties of undefined (reading '_batch')","locations":[{"line":5,"column":5}],"path":["createReflection","reflectionGroup"]}]}`
}
    at executeGraphQL (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:461:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onMessage (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:87764:22)
```
