### ISSUE TITLE
"You found a bug" notification in Demo 

### ISSUE THREAD

**Issue by elielytz** [ParabolInc/parabol#5911]
## Environment
Staging v6.44.0

## Issue - Bug

When the End Timer option is clicked in the timer button, **_"You found a bug"_** notification is popped.
The timer is stopped as expected but you can hardly use the timer feature until you refresh the page or advance to the next step.

<img src="https://user-images.githubusercontent.com/45159239/150486520-3347ec6b-8ce9-49d2-9305-5568c1ccaae0.png" width=65% height=65%>

![demo timer bug](https://user-images.githubusercontent.com/7331043/150562268-c6845ef9-6930-4f45-b922-047d96267cd2.gif)

### Acceptance Criteria (optional)
Users can:
   - [ ] Start and End timer without interruption of bug notification.

**Comment by adaniels-parabol** [comment]
Console error

`TypeError: Cannot read properties of undefined (reading 'auth')
    at StageTimerModalEndTimeSlackToggle.tsx:74:94
    at pe (StageTimerModalEndTimeSlackToggle.tsx:1:556)
    at StageTimerModalEndTimeSlackToggle.tsx:74:47
    at sa (react-dom.production.min.js:157:137)
    at Zs (react-dom.production.min.js:267:460)
    at Al (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Tl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ko (react-dom.production.min.js:122:325)
    at Yo (react-dom.production.min.js:123:61)
    at Qo (react-dom.production.min.js:122:428)
    at hl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at t._.setState (react.production.min.js:12:369)
    at SwipeableViews.js:616:18
    at r (helpers.js:72:23)`

**Comment by Dschoordsch** [comment]
Was fixed on staging before releasing v6.44.0
