### ISSUE TITLE
Jira Server: Send error to client when adding integration fails

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6195]
I tried to add Jira Server locally today & in the server console I saw the following:

```sh
SEND TO SENTRY Error: Requesting OAuth1 request token failed with status 401
    at JiraServerOAuth1Manager.requestToken (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:56063:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.resolve [as MutationcreateOAuth1AuthorizeUrlResolver] (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:9329:19) undefined
```

This won't help customers who try to integrate, so we should improve this.

AC
- [ ] The error message is helpful & includes the error that comes from Jira. (ie replace `Requesting OAuth1 request token failed with status ${response.status}` with an error message that comes from the response
- [ ] That meaningful error messages is displayed under the connect button

Estimate: 5 hours

**Comment by mattkrick** [comment]
Ugh, they sneak the error in a header

```
response.headers.get('www-authenticate')
'OAuth realm="https%3A%2F%2Fjira.parabol.co", OAuth realm="https%3A%2F%2Fjira.parabol.co", oauth_problem="consumer_key_unknown"'
```
