### ISSUE TITLE
RelayNetwork: No data returned for operation `NewMeetingSummaryQuery`, got error(s): op not found NewMeetingSummaryQuery

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6491]
## Issue - Bug

The summary cannot be generated when the user completes the retro demo, error is displayed when clicking the End Demo Meeting

https://action.parabol.co/retrospective-demo/reflect

<img width="1682" alt="Google Chrome-Retro Meeting  Demo Team-002046-20220503" src="https://user-images.githubusercontent.com/4997466/166465716-acf9d164-2815-484c-ad43-74c900899b70.png">

```js
RelayNetwork: No data returned for operation `NewMeetingSummaryQuery`, got error(s):
op not found NewMeetingSummaryQuery

See the error `source` property for more information.
    at t (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:381455)
    at Object.create (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:381727)
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:302734
    at Array.forEach (<anonymous>)
    at e._handleErrorResponse (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:302495)
    at e._handleNext (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:303566)
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:302287
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:390722
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:302271
    at e._schedule (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:301811)
    at e._next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:302243)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:300009)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:383920
    at Set.forEach (<anonymous>)
    at e.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:383890)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:222156)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:383920
    at Set.forEach (<anonymous>)
    at e.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:383890)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:288349)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at Object.next (https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:282163)
    at https://action-files.parabol.co/staging/build/v6.56.0/app_82b046c58fe6c8396244.js:40:283648
```

### Acceptance Criteria (optional)
Users can:
   - End Demo Meeting
   - See the Meeting Summary
   - Cannot see the error page

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by JimmyLv** [comment]
Cool! thanks @nickoferrall let me know. I'm doing the Bug Squashing, and I found this one impacted more than 30 users [here](https://sentry.io/organizations/parabol/issues/?groupStatsPeriod=auto&page=0&project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d).

Just want to double confirm that this issue only occurs at the end of the meeting, when the generation of the `NewMeetingSummary` involves requesting a Jira or GitHub integrated task. So it causes the request error?

**Comment by nickoferrall** [comment]
Yep, that's right! There are two bugs in the demo: 

1. Can't push a task to an integration
2. Ending the demo 

Feel free to review the PR if you like 😃

**Comment by JimmyLv** [comment]
yeah, will have a look! 😁  Should I close this issue? or just leave it here after the PR is merged and fixed for production.
