### ISSUE TITLE
feat(gitlab): Burndown to v1

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6511]
1. placeholder should be smaller (Search gitlab? search gitlab projects? gitlab projects?)
<img width="229" alt="Screen Shot 2022-05-05 at 11 32 40 AM" src="https://user-images.githubusercontent.com/5514175/166995253-0866e4c2-a36f-43af-848a-91bbcc718f0b.png">

2. Filters aren't updating
<img width="736" alt="Screen Shot 2022-05-05 at 11 35 50 AM" src="https://user-images.githubusercontent.com/5514175/166997166-740365ff-4645-4b7c-99fc-e13c81cf4ffe.png">

3. clicking select all is broken 
<img width="676" alt="Screen Shot 2022-05-05 at 11 36 29 AM" src="https://user-images.githubusercontent.com/5514175/166997297-ddc5a2be-ff9d-48f1-a25d-6da1c28b756b.png">

4. searching by issue number is broken
<img width="753" alt="Screen Shot 2022-05-05 at 11 37 50 AM" src="https://user-images.githubusercontent.com/5514175/166997854-0db4f99d-36b3-4186-8801-65fe63e92616.png">

5. query complexity was too high & it tells me i'm not on the team
<img width="370" alt="Screen Shot 2022-05-05 at 11 44 14 AM" src="https://user-images.githubusercontent.com/5514175/167001365-4504db16-3de3-4821-9c3b-19d9df4a7ba6.png">

<summary>see
<details>

```
11:40:36 1|GraphQL Executor  | SEND TO SENTRY Error: Query has complexity of 480, which exceeds max complexity of 250
11:40:36 1|GraphQL Executor  |     at /Users/mattkrick/code/parabol/dev/gqlExecutor.js:57348:30
11:40:36 1|GraphQL Executor  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:40:36 1|GraphQL Executor  |     at async Object.resolve [as TaskintegrationResolver] (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:50941:33) undefined
11:40:37 1|GraphQL Executor  | TypeError: Cannot destructure property 'issue' of 'issueData' as it is undefined.
11:40:37 1|GraphQL Executor  |     at Object.resolve [as EstimateStageserviceFieldResolver] (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:39655:13)
11:40:37 1|GraphQL Executor  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:40:37 1|GraphQL Executor  | Trace: {
11:40:37 1|GraphQL Executor  |   error: `{"data":{"viewer":{"isConnected":true,"meeting":null,"id":"google-oauth2|d1Y7ewQPjW"}},"errors":[{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",0,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",1,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",2,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",3,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",4,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",5,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",6,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",7,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",8,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",9,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",10,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",11,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",12,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",13,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",14,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",15,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",16,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",17,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",18,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",19,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",20,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",21,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",22,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",23,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",24,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",25,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"line":764,"column":3},{"line":1469,"column":3},{"line":1505,"column":3}],"path":["viewer","meeting","phases",1,"stages",26,"serviceField"]},{"message":"Cannot destructure property 'issue' of 'issueData' as it is undefined.","locations":[{"line":658,"column":3},{"line":652,"column":3},{"line":955,"column":3},{"line":934,"column":3},{"line":770,"column":3},{"l`... 858 more characters
11:40:37 1|GraphQL Executor  | }
11:40:37 1|GraphQL Executor  |     at executeGraphQL (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:615:13)
11:40:37 1|GraphQL Executor  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:40:37 1|GraphQL Executor  |     at async onMessage (/Users/mattkrick/code/parabol/dev/gqlExecutor.js:97000:22)
11:40:37 2|Socket Server     | SEND TO SENTRY [Error: Cannot destructure property 'issue' of 'issueData' as it is undefined.] 
undefined
```

</details>
</summary>

**Comment by mattkrick** [comment]
the last issue is really bad. i can't get back into the meeting, i.e. the entire meeting is borked.
after fixing these issues we can do a retest, but for now we need to keep this behind feature flag

**Comment by nickoferrall** [comment]
@mattkrick thanks for digging into the integration and creating this issue!

1. I've updated the placeholder. As it just required removing `from` from the string, I pushed the update to master [here](https://github.com/ParabolInc/parabol/commit/2149b0596d10a5ae9fdda65e2c2646fe6326e8db). 
![new-placeholder](https://user-images.githubusercontent.com/39854876/167009628-5e870968-88cd-4cc4-9c11-15236a889be2.png)

2. The filters are working for me in prod and master, but I'd be happy to ask someone else if they're not updating for them. 

<details>

![gitlab-filters](https://user-images.githubusercontent.com/39854876/167010336-843c4a13-6662-4642-8517-662547ed4f5a.gif)

</details> 

3. Select all functionality is broken for all integrations - it's not related to GitLab. I've created a PR https://github.com/ParabolInc/parabol/pull/6439 to fix this.
4. GitLab's search query only searches for issue titles. In the GitLab app, it's not possible to search for issue numbers. I don't think we need this for v1, but I can create a v2 issue for this if you like? 
<details>

![gitlab-issue-num-gif](https://user-images.githubusercontent.com/39854876/167011573-1d4441c3-0e09-4427-b9c0-eb6a36c2b89c.gif)

</details>

5. That's concerning - I ran into a query complexity issue after clicking Select All. That was fixed by https://github.com/ParabolInc/parabol/pull/6439 for me, but it looks like you're running into the issue after trying to join a team? Any repro steps you can remember? If it's unrelated to the select all functionality, I suspect the nested query will need to be refactored before v1 can be released.
