### ISSUE TITLE
Retro email summary not working

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6522]
## Issue - Bug

Currently, when a server tries to send the retro email summery it gets the following error
```
15:16:54 1|GraphQL Executor  | Invariant Violation: useRelayEnvironment: Expected to have found a Relay environment provided by a `RelayEnvironmentProvider` component. This usually means that useRelayEnvironment was used in a component that is not a descendant of a `RelayEnvironmentProvider`. Please make sure a `RelayEnvironmentProvider` has been rendered somewhere as a parent or ancestor of your component.
15:16:54 1|GraphQL Executor  |     at invariant (/Users/bjarocki/Work/parabol/web-parabol/node_modules/invariant/invariant.js:40:15)
15:16:54 1|GraphQL Executor  |     at useRelayEnvironment (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-relay/lib/relay-hooks/useRelayEnvironment.js:23:64)
15:16:54 1|GraphQL Executor  |     at useLazyLoadQuery (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-relay/lib/relay-hooks/useLazyLoadQuery.js:30:21)
15:16:54 1|GraphQL Executor  |     at MeetingSummaryEmailRootSSR (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:84552:77)
15:16:54 1|GraphQL Executor  |     at processChild (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
15:16:54 1|GraphQL Executor  |     at resolve (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
15:16:54 1|GraphQL Executor  |     at ReactDOMServerRenderer.render (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
15:16:54 1|GraphQL Executor  |     at ReactDOMServerRenderer.read (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
15:16:54 1|GraphQL Executor  |     at Object.renderToStaticMarkup (/Users/bjarocki/Work/parabol/web-parabol/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
15:16:54 1|GraphQL Executor  |     at renderSSRElement (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:95539:59)
15:16:54 1|GraphQL Executor  |     at newMeetingSummaryEmailCreator (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:95413:90)
15:16:54 1|GraphQL Executor  |     at sendNewMeetingSummary (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:9845:141)
15:16:54 1|GraphQL Executor  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
15:16:54 1|GraphQL Executor  |   framesToPop: 1
15:16:54 1|GraphQL Executor  | }
```

### Acceptance Criteria (optional)
- [ ] retro email summary works 
- [ ] check-in email summary works
- [ ] sprint poker email summary works

**Estimated effort:** 8h

**Comment by jordanh** [comment]
Thank you for jumping on this @BartoszJarocki, @Dschoordsch
