### ISSUE TITLE
Demo: toggle slack end meeting message fails

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6620]
From the error it appears as if a demo user tried to toggle the endMeeting slack toggle but it failed because of recent MS Teams changes.

TypeError: Cannot read properties of undefined (reading 'auth')

https://sentry.io/organizations/parabol/issues/3284049307/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'auth')
  at fn (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:75:88)
  at _optionalChain (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:1:556)
  at c (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:75:44)
...
(14 additional frame(s) were not displayed)
```

**Comment by JimmyLv** [comment]
should relate to this change:
- feat: Notifications support for MS Teams (#6494)

https://github.com/ParabolInc/parabol/issues/6626#issuecomment-1137348831
