### ISSUE TITLE
Clicking on '6 active meetings' in New Meeting view caused error

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6621]
https://sentry.io/organizations/parabol/issues/3289944527/?referrer=github_plugin

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at Vg (./node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
  at Zg (./node_modules/react-dom/cjs/react-dom.production.min.js:149:163)
  at fi (./node_modules/react-dom/cjs/react-dom.production.min.js:176:171)
  at ck (./node_modules/react-dom/cjs/react-dom.production.min.js:271:134)
  at bk (./node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
...
(10 additional frame(s) were not displayed)
```

**Comment by BartoszJarocki** [comment]
@Dschoordsch that's already fixed here: https://github.com/ParabolInc/parabol/pull/6611

**Comment by Dschoordsch** [comment]
@BartoszJarocki you commented faster than I could add that this had happened to James.

**Comment by BartoszJarocki** [comment]
👀 😅
