### ISSUE TITLE
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6727]
Seen for the first time on 6.61.0, affected 41 users. 

https://sentry.io/organizations/parabol/issues/3337367113/?referrer=github_plugin

```
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
  at Ch (./node_modules/react-dom/cjs/react-dom.production.min.js:157:334)
  at li (./node_modules/react-dom/cjs/react-dom.production.min.js:180:154)
  at ck (./node_modules/react-dom/cjs/react-dom.production.min.js:269:343)
  at bk (./node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
  at ak (./node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
...
(8 additional frame(s) were not displayed)
```

**Comment by BartoszJarocki** [comment]
Sentry issue: [ACTION-PRODUCTION-B05](https://sentry.io/organizations/parabol/issues/3245993082/?referrer=github_plugin)

**Comment by jordanh** [comment]
No longer occurring in Sentry. Presuming fixed
