### ISSUE TITLE
Error: Element type is invalid: expected a string but got: undefined

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6729]
7 users affected

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at Vg (./node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
  at Yg (./node_modules/react-dom/cjs/react-dom.production.min.js:149:163)
  at fi (./node_modules/react-dom/cjs/react-dom.production.min.js:176:186)
  at mi (./node_modules/react-dom/cjs/react-dom.production.min.js:179:470)
  at ck (./node_modules/react-dom/cjs/react-dom.production.min.js:274:466)
...
(10 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
@BartoszJarocki there is no link to the Sentry issue! I will icebox :)
