### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.auth')

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6784]
https://sentry.io/organizations/parabol/issues/3340565152/?referrer=github_plugin

```
TypeError: undefined is not an object (evaluating 'e.auth')
  at fn (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:75:85)
  at _optionalChain (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:1:556)
  at None (./packages/client/components/StageTimerModalEndTimeSlackToggle.tsx:75:44)
  at yl ([native code])
  at identifier (./packages/client/components/Action/Action.tsx:40:21)
...
(14 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
As of now, affects 1 user, happened 11 times.

AC: - spend 1 hour to triage and fix, or triage and open a new issue

**Comment by jordanh** [comment]
No longer occurs in Sentry. Presuming fixed and closing
