### ISSUE TITLE
TypeError: null is not an object (evaluating 'window.localStorage.getItem')

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#6912]
https://sentry.io/organizations/parabol/issues/3040564182/?referrer=github_plugin

**Affected users in the last 24h:** 0 users (but 9 in the last 30 days)
**First seen:** 5 months ago

```
TypeError: null is not an object (evaluating 'window.localStorage.getItem')
  at None (./packages/client/components/AnalyticsPage.tsx:111:26)
  at Object (./packages/client/components/Action/Action.tsx:40:21)
  at F (./packages/client/components/Action/Action.tsx:40:21)
  at None (./packages/client/components/Action/Action.tsx:40:21)
...
(1 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Did not see any instances in Sentry history, presumed fixed
