### ISSUE TITLE
Release build fails with sharp not finding a dependency

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7161]
We cannot release as the deploy fails. [Slack thread](https://parabol.slack.com/archives/C836NA350/p1662453269485389)

## Error
Currently our dokku deploy fails with
```
remote:        Error:         
remote:        Something went wrong installing the "sharp" module        
remote:        node-loader:        
remote:        Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory        
remote:        Possible solutions:        
remote:        - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"        
remote:        - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"        
remote:        - Consult the installation documentation: https://sharp.pixelplumbing.com/install        
remote:            at Object.65939 (/app/dist/web.js:616176:9)        
remote:            at __webpack_require__ (/app/dist/web.js:882083:42)        
remote:            at Object.26955 (/app/dist/web.js:612370:1)        
remote:            at __webpack_require__ (/app/dist/web.js:882083:42)        
remote:            at Object.66456 (/app/dist/web.js:612759:15)        
remote:            at __webpack_require__ (/app/dist/web.js:882083:42)        
remote:            at Object.97198 (/app/dist/web.js:70699:17)        
remote:            at __webpack_require__ (/app/dist/web.js:882083:42)        
remote:            at Object.89779 (/app/dist/web.js:96787:18)        
remote:            at __webpack_require__ (/app/dist/web.js:882083:42)  
```

## Investigation
Diff between last working and not failing build https://github.com/ParabolInc/parabol/compare/v6.72.1...v6.73.0-rc.1

What has been tried so far:
* reverting sharp version from 0.30.7 back to 0.30.5
* reverting build image back from cimg/base:2022.07 to cimg/node:16.14.0

`libvips-cpp.so.42` file is present in both failing and passing builds. It is in a subfolder of sharps dependencies. This means loading the shared library fails. `ldd` can resolve all dependencies of the library on both working and broken systems, so it is probably a library search path issue.
Since #6965 needed to install libvips system wide to successfully build, it probably introduced the error.

**Comment by Dschoordsch** [comment]
Reverting #6965 solved the issue.
