### ISSUE TITLE
Error on /tasks after accepting an invite

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7259]
https://sentry.io/organizations/parabol/issues/1928985777/?referrer=github_plugin

```
TypeError: Cannot destructure property 'user' of 'undefined' as it is undefined.
  at None (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:138:37)
  at Array.map (<anonymous>)
  at a (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:138:31)
  at c (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:136:32)
  at Set.forEach (<anonymous>)
...
(36 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Still occurring. Watermark: 18 times in last 30, 39 users total

Will keep open.

**Comment by jordanh** [comment]
![image](https://github.com/ParabolInc/parabol/assets/103000/8ba01fd2-abb4-4960-bad6-43dac9ab43c1)

**Comment by mwermuth** [comment]
Came up during backlog scrubbing. Still happening but only 3 times in the past 30 days for a total of 8 users. Leaving it open as this could be related to invites.

Going to close it if it shows up as stale next time.

**Comment by jordanh** [comment]
Scrubbed. @Dschoordsch did we fix this one? Can we close?

**Comment by Dschoordsch** [comment]
I do not recall any specific fix for this, but the issue is gone, so let's just close it.
