### ISSUE TITLE
Users getting an error when trying to leave team: `TypeError removeTeamMemberTeamUpdater`

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7311]
https://sentry.io/organizations/parabol/issues/3669001466/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d

29 events 14 users

```
TypeError: Cannot read properties of null (reading 'map')
  at removeTeamMemberTeamUpdater (./packages/client/mutations/RemoveTeamMemberMutation.ts:157:49)
  at removeTeamMemberUpdater (./packages/client/mutations/RemoveTeamMemberMutation.ts:164:3)
  at updater (./packages/client/mutations/RemoveTeamMemberMutation.ts:177:7)
  at Set.forEach (<anonymous>)
  at filterTeamMember (./packages/client/utils/relay/filterTeamMember.ts:5:3)
...
(16 additional frame(s) were not displayed)
```

User feedback

> Tried to leave a team, and got an error after clicked "leave" button.

**Comment by jordanh** [comment]
Possibly related (or at least in the same neighborhood) as: https://github.com/ParabolInc/parabol/issues/6424

**Comment by JimmyLv** [comment]
This issue occurs when leaving the team. When cleaning up the member's task list, an error occurs when the team member's `tasks` is `null`.
I explained the details in https://github.com/ParabolInc/parabol/pull/7368, which should be fixed after it is merged.
