### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getValue')

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7449]
Happened 20 times in the last 30 days. First seen in 6.78.1

https://sentry.io/organizations/parabol/issues/3669667896/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'getValue')
  at call (./packages/client/mutations/UpdateTaskMutation.ts:74:27)
  at _ (./packages/client/subscriptions/TaskSubscription.ts:1:440)
  at fn (./packages/client/subscriptions/TaskSubscription.ts:60:53)
  at _optionalChain (./packages/client/subscriptions/TaskSubscription.ts:1:418)
  at updater (./packages/client/subscriptions/TaskSubscription.ts:60:7)
...
(27 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
Happened 122 times last 30 days, increasing priority

**Comment by jmtaber129** [comment]
Seen 10 times last 30 days, decreasing priority

**Comment by mwermuth** [comment]
Came up during backlog scrubbing. Still happening 5 times in the last 30 days. But it doesn't seem to be an important issue. Closing for now.
