### ISSUE TITLE
End meeting: Pressing end meeting CTA in check-in terminates the meeting instead

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7453]
During smoke test after releasing #7439 we found that when pressing the "End meeting" CTA at the end of a check-in would terminate the meeting instead of properly ending it.

# Expected behaviour
"End meeting" CTA behaves the same as "End meeting" button in action bar.

# Actual behaviour
Pressing the "End meeting" CTA did terminate the meeting
* meeting was terminated snack was shown
* no summary
* agenda items were not closed

I could reproduce it locally once with 6.70.0, so this is not a new issue. I could however not reproduce it reliably anymore since then.

**Comment by Dschoordsch** [comment]
The one time I could reproduce it locally I saw
```
12:41:23 1|GraphQL Executor | ReferenceError: window is not defined
12:41:23 1|GraphQL Executor |     at Object../packages/client/hooks/useResizeObserver.ts (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:94551:24)
12:41:23 1|GraphQL Executor |     at __webpack_require__ (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:109282:41)
12:41:23 1|GraphQL Executor |     at Object../packages/client/hooks/useCoords.ts (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:93152:76)
12:41:23 1|GraphQL Executor |     at __webpack_require__ (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:109282:41)
12:41:23 1|GraphQL Executor |     at Object../packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:90103:74)
12:41:23 1|GraphQL Executor |     at __webpack_require__ (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:109282:41)
12:41:23 1|GraphQL Executor |     at Object../packages/client/components/EditorLinkChanger/EditorLinkChangerTipTap.tsx (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:90328:81)
12:41:23 1|GraphQL Executor |     at __webpack_require__ (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:109282:41)
12:41:23 1|GraphQL Executor |     at Object../packages/client/components/promptResponse/PromptResponseEditor.tsx (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:92553:100)
12:41:23 1|GraphQL Executor |     at __webpack_require__ (/home/man/Work/parabol/parabol/dev/gqlExecutor.js:109282:41)
```
This was on 6.70.0 and could be unrelated.

**Comment by jordanh** [comment]
This bug has been haunting us _for years_. I wish we could figure it out.

**Comment by jmtaber129** [comment]
Is this bug specific to the CTA? Or have we seen it with the normal button, too?

I investigated this a bit, and found that if you skip a stage before the agenda (e.g. a team member's icebreaker), the logic we use to determine the meeting phase doesn't work correctly - we look for the first phase for which there exists a stage that is not complete. So if you skip an icebreaker or team member update, the phase we determine is the current phase will be either "icebreaker" or "solo updates".

We determine whether a check-in meeting is a termination based on whether the current phase is "agenda items" or "last call", so skipping an earlier stage would lead to a termination.

A fix could be updating the `getMeetingPhase` function to consider the last phase with a completed stage, and the current facilitator stage.

**Comment by Dschoordsch** [comment]
I cannot say with certainty that we did not do earlier stages out of order. We did jump around in the agenda stage, but we did not skip any stage.
I only observed this on the CTA, not the normal button, but I cannot reliably reproduce this issue so I don't know if it's limited to that one.
