### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for com...

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7611]
https://sentry.io/organizations/parabol/issues/3755892312/?referrer=github_plugin

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at Vg (./node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
  at Yg (./node_modules/react-dom/cjs/react-dom.production.min.js:149:163)
  at fi (./node_modules/react-dom/cjs/react-dom.production.min.js:176:186)
  at mi (./node_modules/react-dom/cjs/react-dom.production.min.js:179:470)
  at ck (./node_modules/react-dom/cjs/react-dom.production.min.js:274:466)
...
(10 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
19 users, 20 events

**Comment by mwermuth** [comment]
Still existing. Occurred 10 times in the last 30 days. Worth to keep it open still and check back in.

**Comment by jordanh** [comment]
Issue no longer occurs
