### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7717]
https://sentry.io/organizations/parabol/issues/3683876346/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'map')
  at removeOrgUserTeamUpdater (./packages/client/mutations/RemoveOrgUserMutation.ts:139:50)
  at <object>.updater (./packages/client/mutations/RemoveOrgUserMutation.ts:244:7)
  at Set.forEach (<anonymous>)
  at setConnectedStatus (./packages/client/hooks/useTrebuchetEvents.ts:20:7)
  at onDisconnected (./packages/client/hooks/useTrebuchetEvents.ts:33:7)
...
(10 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
Happened 40 times in the last 30 days.
