### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getValue')

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7718]
https://sentry.io/organizations/parabol/issues/3844612424/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'getValue')
  at removeReflectionMeetingUpdater (./packages/client/mutations/RemoveReflectionMutation.ts:62:43)
  at <object>.updater (./packages/client/mutations/RemoveReflectionMutation.ts:84:7)
  at Set.forEach (<anonymous>)
  at watchForClick (./packages/client/components/RetroReflectPhase/ExpandedReflection.tsx:34:9)
...
(8 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
Happened 27 times in the last 30 days
