### ISSUE TITLE
RelayNetwork: No data returned for operation `InvitationLinkQuery`, got error(s):

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7776]
Could be related to #7771

https://parabol.sentry.io/issues/3934812478/?referrer=github_plugin

```
RelayNetwork: No data returned for operation `InvitationLinkQuery`, got error(s):
The request took too long

See the error `source` property for more information.
  at message (./node_modules/relay-runtime/lib/util/RelayError.js:24:3)
  at module.exports.create (./node_modules/relay-runtime/lib/util/RelayError.js:52:5)
  at 63898/t._handleErrorResponse/k< (./node_modules/relay-runtime/lib/store/OperationExecutor.js:374:13)
  at _proto._handleErrorResponse (./node_modules/relay-runtime/lib/store/OperationExecutor.js:389:5)
  at _proto._handleNext (./node_modules/relay-runtime/lib/store/OperationExecutor.js:439:29)
...
(20 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Possibly related to: https://github.com/ParabolInc/parabol/issues/5439

**Comment by jordanh** [comment]
Watermark: 21 events, 16 users
