### ISSUE TITLE
TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8088]
https://parabol.sentry.io/issues/4011330637/?referrer=github_plugin

```
TypeError: Right side of assignment cannot be destructured
  at <anonymous> (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:110:24)
  at forEach ([native code])
  at sortedAvatars (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:107:17)
  at j (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:104:25)
  at yl ([native code])
...
(45 additional frame(s) were not displayed)
```

Very similar to #8084

**Comment by jordanh** [comment]
17 users, 16 events in the past 30 days
