### ISSUE TITLE
TypeError: Cannot destructure property 'user' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8091]
https://parabol.sentry.io/issues/4076046545/?referrer=github_plugin

```
TypeError: Cannot destructure property 'user' of 'undefined' as it is undefined.
  at users (./packages/client/components/PokerVotingRow.tsx:48:30)
  at Array.map (<anonymous>)
  at ia (./packages/client/components/PokerVotingRow.tsx:48:24)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(34 additional frame(s) were not displayed)
```

10 events, 10 users

**Comment by mwermuth** [comment]
Still showing up 35 times in the past 30 days.

**Comment by jordanh** [comment]
34 users in the past 30 days, keeping open
