### ISSUE TITLE
User can be undefined in UserTasksHeader

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8239]
Affected 12 users over the past 25 days

https://parabol.sentry.io/issues/4133300635/?referrer=github_plugin

```
TypeError: Cannot destructure property 'user' of 'undefined' as it is undefined.
  at users (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:142:37)
  at Array.map (<anonymous>)
  at teamMemberFilterName (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:142:31)
  at M (./packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx:140:32)
  at Set.forEach (<anonymous>)
...
(37 additional frame(s) were not displayed)
```

**Comment by mwermuth** [comment]
Still happening 22 times in the past 30 days. Keeping it open as p3.

**Comment by jordanh** [comment]
Issue no longer occurs
