### ISSUE TITLE
Unable to destructure the commentId in discussions

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8240]
Affected 22 users over the past month

https://parabol.sentry.io/issues/4079122397/?referrer=github_plugin

```
TypeError: Cannot destructure property 'id' of 'p' as it is undefined.
  at Le (./packages/client/components/ThreadedCommentBase.tsx:114:9)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(32 additional frame(s) were not displayed)
```

**Comment by nickoferrall** [comment]
@rafaelromcar-parabol ran into this on staging. When he had comments in the discussion thread, and he was disconnected, he got an error with this error message in the console.

When he didn't have a comment in the discussion thread, he didn't get an error when disconnecting.

**Comment by jordanh** [comment]
Issue no longer occurs
