### ISSUE TITLE
ERROR [app build 10/10] RUN yarn build

### ISSUE THREAD

**Issue by johnfelipe** [ParabolInc/parabol#8492]
this is my local server:

    Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-30-generic x86_64)

path:

	root@template:~/parabol# pwd
	/root/parabol

this is my steps:

	docker compose version

	Docker Compose version v2.18.1

this docker version

	docker --version

	Docker version 24.0.4, build 3713ee1

then clone

	git clone https://github.com/ParabolInc/parabol.git

	cd parabol
	cp .env.example .env

edit file env

	nano /root/parabol/.env

	##
	#FILE_STORE_PROVIDER='s3'
	FILE_STORE_PROVIDER='local'
	##
	
and docker

    docker compose -f docker-compose.yml -f ./docker/docker-compose.selfHosted.yml up -d

and this is error:

	[+] Running 27/27
	 ✔ redis 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                         16.9s
	   ✔ faef57eae888 Pull complete                                           13.3s
	   ✔ bb595d48e52d Pull complete                                           13.3s
	   ✔ d479b54c3bb2 Pull complete                                           13.3s
	   ✔ dfca1dd212ea Pull complete                                           14.6s
	   ✔ 9eea383ab9b1 Pull complete                                           14.6s
	   ✔ 0f7a39f02c6d Pull complete                                           14.6s
	 ✔ db 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                              8.5s
	   ✔ 9d21b12d5fab Pull complete                                            5.5s
	   ✔ 00e81c4c5261 Pull complete                                            6.0s
	   ✔ d0f27f163c2b Pull complete                                            6.0s
	   ✔ 685dcea274ee Pull complete                                            6.2s
	   ✔ e6b78885a9ad Pull complete                                            6.3s
	 ✔ postgres 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled              17.6s
	   ✔ 214ca5fb9032 Pull complete                                            7.1s
	   ✔ e6930973d723 Pull complete                                            7.3s
	   ✔ aea7c534f4e1 Pull complete                                            7.3s
	   ✔ d0ab8814f736 Pull complete                                            7.4s
	   ✔ 648cc138980a Pull complete                                            8.0s
	   ✔ 7804b894301c Pull complete                                            8.1s
	   ✔ cfce56252c3f Pull complete                                            8.1s
	   ✔ 8cce7305e3b6 Pull complete                                            8.1s
	   ✔ 756153ea087d Pull complete                                           15.3s
	   ✔ ea97ffe1aac8 Pull complete                                           15.3s
	   ✔ c8860bfd3d19 Pull complete                                           15.3s
	   ✔ 3da507ad8728 Pull complete                                           15.3s
	   ✔ 4b26ff498733 Pull complete                                           15.3s
	[+] Building 258.9s (15/20)
	[+] Building 259.0s (15/20)
	[+] Building 259.2s (15/20)
	[+] Building 272.3s (16/20)
	 => [app internal] load .dockerignore                                      0.0s
	 => => transferring context: 2B                                            0.0s
	 => [app internal] load build definition from Dockerfile.prod              0.0s
	 => => transferring dockerfile: 1.55kB                                     0.0s
	 => [app internal] load metadata for docker.io/library/node:18.16.0        1.6s
	 => [app build  1/10] FROM docker.io/library/node:18.16.0@sha256:4a55308  33.0s
	 => => resolve docker.io/library/node:18.16.0@sha256:4a55308cc855cba1a925  0.0s
	 => => sha256:b7b4409e470d10d87b1772cb68a802be111e85bc9ec 2.00kB / 2.00kB  0.0s
	 => => sha256:8e81ac769c958d05f1bc43df0bfbce0f609e2a36c8e 7.24kB / 7.24kB  0.0s
	 => => sha256:4a55308cc855cba1a925d19ae4e45838741dad2fd7b 1.21kB / 1.21kB  0.0s
	 => => sha256:ec2b820b8e87758dde67c29b25d4cbf88377601a4 24.03MB / 24.03MB  4.3s
	 => => sha256:284f2345db055020282f6e80a646f1111fb2d5dfc 64.11MB / 64.11MB  8.5s
	 => => sha256:bba7bb10d5baebcaad1d68ab3cbfd37390c646b2a 49.55MB / 49.55MB  4.0s
	 => => sha256:fea23129f080a6e28ebff8124f9dc585b412b1 211.00MB / 211.00MB  15.9s
	 => => extracting sha256:bba7bb10d5baebcaad1d68ab3cbfd37390c646b2a688529b  4.3s
	 => => sha256:9063cd8e310682d6ca55554ed439d2618090ac91560 3.37kB / 3.37kB  4.5s
	 => => sha256:e6fac8ec5874a08556a07e764989d76b135f8644 45.52MB / 45.52MB  10.5s
	 => => sha256:689a3a390764baa467add430488952885b461586107 2.28MB / 2.28MB  8.9s
	 => => extracting sha256:ec2b820b8e87758dde67c29b25d4cbf88377601a4355cc5d  1.5s
	 => => sha256:c976cd2164455ed28f44068f393be99dd9434cd2cb03992 451B / 451B  9.1s
	 => => extracting sha256:284f2345db055020282f6e80a646f1111fb2d5dfc6f7ee87  6.0s
	 => => extracting sha256:fea23129f080a6e28ebff8124f9dc585b412b1a358bba56  12.2s
	 => => extracting sha256:9063cd8e310682d6ca55554ed439d2618090ac91560855be  0.0s
	 => => extracting sha256:e6fac8ec5874a08556a07e764989d76b135f86442c973e19  4.0s
	 => => extracting sha256:689a3a390764baa467add430488952885b4615861077f74d  0.1s
	 => => extracting sha256:c976cd2164455ed28f44068f393be99dd9434cd2cb03992e  0.0s
	 => [app internal] load build context                                      2.2s
	 => => transferring context: 143.81MB                                      2.2s
	 => [app build  2/10] WORKDIR /parabol                                     0.5s
	 => [app build  3/10] COPY package.json yarn.lock ./                       0.0s
	 => [app build  4/10] COPY packages/client/package.json ./packages/client  0.0s
	 => [app build  5/10] COPY packages/gql-executor/package.json packages/gq  0.0s
	 => [app build  6/10] COPY packages/integration-tests/package.json packag  0.0s
	 => [app build  7/10] COPY packages/server/package.json packages/server/p  0.0s
	 => [app prod  8/13] RUN yarn install --prod --frozen-lockfile &&        161.0s
	 => [app build  8/10] RUN yarn install --frozen-lockfile &&       yarn   216.4s
	 => [app prod  9/13] COPY . .                                              0.6s
	 => [app build  9/10] COPY . .                                             0.7s
	 => ERROR [app build 10/10] RUN yarn build                                20.0s ------                                                                           > [app build 10/10] RUN yarn build:                                            0.498 yarn run v1.22.19
	0.574 $ node scripts/prod.js
	6.495 🙏🙏🙏      Building Production Server      🙏🙏🙏
	6.914 (node:30) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
	6.914
	6.914 Please migrate your code to use AWS SDK for JavaScript (v3).
	6.914 For more information, check the migration guide at https://a.co/7PzMCcy
	6.914 (Use `node --trace-warnings ...` to show where the warning was created)
	19.79 webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4
	19.79 var _getUsersByIdsQuery = __webpack_require__(Object(function webpackMissingModule() { var e = new Error("Cannot find module './generated/getUsersByIdsQuery'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
	19.79                                                                                                ^
	19.79
	19.79 Error: Cannot find module './generated/getUsersByIdsQuery'
	19.79     at webpackMissingModule (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4:96)
	19.79     at eval (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4:201)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:410:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/utils/segmentIo.ts?:2:22)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:396:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/graphql/mutations/addAgendaItem.ts?:9:18)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:249:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/graphql/rootMutation.ts?:2:22)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:242:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/graphql/public/rootSchema.ts?:17:21)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:200:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/graphql/private/rootSchema.ts?:3:19)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:165:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at eval (webpack://parabol-action/./packages/server/utils/updateGQLSchema.ts?:11:19)
	19.79     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:151:1)
	19.79     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10949:41)
	19.79     at /parabol/scripts/toolbox/updateSchema.js:11069:37
	19.79     at Object.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:11074:12)
	19.79     at Module._compile (node:internal/modules/cjs/loader:1254:14)
	19.79     at Module._compile (/parabol/node_modules/pirates/lib/index.js:136:24)
	19.79     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	19.79     at Object.newLoader [as .js] (/parabol/node_modules/pirates/lib/index.js:141:7)
	19.79     at Module.load (node:internal/modules/cjs/loader:1117:32)
	19.79     at Module._load (node:internal/modules/cjs/loader:958:12)
	19.79     at Module.require (node:internal/modules/cjs/loader:1141:19)
	19.79     at require (node:internal/modules/cjs/helpers:110:18)
	19.79     at updateGraphQLSchema (/parabol/scripts/runSchemaUpdater.ts:27:10)
	19.79     at runSchemaUpdater (/parabol/scripts/runSchemaUpdater.ts:32:10)
	19.79     at async generateGraphQLArtifacts (/parabol/scripts/generateGraphQLArtifacts.js:10:3)
	19.79     at async prod (/parabol/scripts/prod.js:25:3) {
	19.79   code: 'MODULE_NOT_FOUND'
	19.79 }
	19.79
	19.79 Node.js v18.16.0
	19.88 error Command failed with exit code 1.

how can fix this?

**Comment by johnfelipe** [comment]
Anyone?

**Comment by Dschoordsch** [comment]
I think the docker-compose file you were using is outdated. Your build is missing artefacts which are created during build, but need a running database and running the migrations first.

A better starting point for you would be https://github.com/paul-vd/parabol/blob/master/docker/parabol-ubi/docker-build/README.md
This is where current progress is made for dockerizing Parabol.

**Comment by Dschoordsch** [comment]
@johnfelipe I'll close this for now. Feel free to add any updates if you've tried this and then I can reopen the issue.
