### ISSUE TITLE
TypeError: Cannot destructure property 'name' of 'd' as it is undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8524]
https://parabol.sentry.io/issues/4277781086/?referrer=github_plugin

```
TypeError: Cannot destructure property 'name' of 'd' as it is undefined.
  at r (./packages/client/utils/useTemplateDescription.ts:31:16)
  at x (./packages/client/modules/meeting/components/ReflectTemplateDetails.tsx:109:23)
  at Set.forEach (<anonymous>)
  at errorCheckerSink.next (./packages/client/Atmosphere.ts:314:25)
...
(33 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
8 users, 8 events last 30 days
