### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8525]
https://parabol.sentry.io/issues/4312123678/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'filter')
  at call (./packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx:132:17)
  at Array.flatMap (<anonymous>)
  at value (./packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx:1:440)
  at selectedOrgTeamMemberEmails (./packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx:131:142)
  at selectedOrgTeamMemberEmails (./packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx:1:418)
...
(37 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
89 events, 84 users

**Comment by Dschoordsch** [comment]
Close in favour of #8525
