### ISSUE TITLE
TypeError: Cannot destructure property 'preferredName' of 'r' as it is null.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8952]
https://parabol.sentry.io/issues/4077054312/?referrer=github_plugin

```
TypeError: Cannot destructure property 'preferredName' of 'r' as it is null.
  at C (./packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatar.tsx:63:10)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(31 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Issue no longer occurs
