### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'orgId')

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9173]
https://parabol.sentry.io/issues/4537628565/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'orgId')
  at defaultOrgId (./packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx:162:80)
  at _nullishCoalesce (./packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx:1:89)
  at Je (./packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx:162:24)
...
(10 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
87 events, 25 users. Related to one on one team check.

**Comment by Dschoordsch** [comment]
Might be related to #9172, worth just waiting for the next release and see if it's fixed.

**Comment by Dschoordsch** [comment]
It still appears in https://github.com/ParabolInc/parabol/releases/tag/v7.13.0

**Comment by jordanh** [comment]
Prioritized to Backlog

**Comment by jordanh** [comment]
Keeping on the backlog.

634 events, 45 users.

**Comment by jordanh** [comment]
Issue no longer occurs
