### ISSUE TITLE
TypeError: Cannot destructure property 'question' of 'i' as it is undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9174]
https://parabol.sentry.io/issues/4295679487/?referrer=github_plugin

```
TypeError: Cannot destructure property 'question' of 'i' as it is undefined.
  at w (./packages/client/components/ReflectionCard/ColorBadge.tsx:53:10)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(31 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
64 events, 21 users.

**Comment by Dschoordsch** [comment]
Seems to happen in meeting summaries

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-EWD](https://parabol.sentry.io/issues/4295679432/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Linking another Sentry issue here because they happen in the same situation in the meeting summary and most likely have the same root cause
```
TypeError
Cannot read properties of null (reading 'map')

./packages/client/components/ReflectionCard/ReactjiSection.tsx in w at line 37:5
In App

32
        id
33
        count
34
        isViewerReactji
35
      }
36
    `,
37
    reactjisRef
[Open this line in GitHub](https://github.com/ParabolInc/parabol/blob/1da6a4dd1f52cb4662475ca7120d841e6bdd342f/packages/client/components/ReflectionCard/ReactjiSection.tsx#L37)
```

**Comment by jordanh** [comment]
14 users in the past 30 days, keeping open
