### ISSUE TITLE
TypeError: Cannot destructure property 'reflections' of 'i' as it is undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9176]
https://parabol.sentry.io/issues/4338475663/?referrer=github_plugin

```
TypeError: Cannot destructure property 'reflections' of 'i' as it is undefined.
  at $ (./packages/client/components/DiscussPhaseReflectionGrid.tsx:57:10)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(32 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Issue no longer occurs.
