### ISSUE TITLE
TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#9206]
17 events 12 users

https://parabol.sentry.io/issues/4114556815/?referrer=github_plugin

```
TypeError: Right side of assignment cannot be destructured
  at ge (./packages/client/components/NewMeetingCheckIn.tsx:72:22)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(29 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Iceboxing
