### ISSUE TITLE
TypeError: Cannot destructure property 'preferredName' of 'g' as it is undefined.

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#9337]
38 events 24 users
https://parabol.sentry.io/issues/4416882317/?referrer=github_plugin

```
TypeError: Cannot destructure property 'preferredName' of 'g' as it is undefined.
  at h (./packages/client/hooks/useSnacksForNewMeetings.ts:46:12)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
  at errorCheckerSink.next (./packages/client/Atmosphere.ts:316:25)
...
(44 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Issue no longer occurs
