### ISSUE TITLE
Failing to create reflection on 7.19.7

### ISSUE THREAD

**Issue by svenseeberg** [ParabolInc/parabol#9487]
## Issue - Bug

- **How serious is the bug?** P0 - P4
- **OS:** macOS / Linux / Windows / ? Linux
- **Browser:** Chrome / Safari / Lynx / ? All
- **Node version:** v20.11.1
- **NPM version:** 10.2.4
- **RethinkDB version:** rethinkdb 2.4.4~0bullseye

When submitting cards in the reflect phase of a retro, the JS console of the browser shows an error and the cards are not saved. The server answers with
```
[
  {
    "message": "Server error",
    "path": [
      "createReflection"
    ]
  }
]
```

The server log from start up to error (I'm not sure if the errors in the server log are in any way related):

```
Mar 01 13:07:17 parabol.example.com yarn[2364893]: yarn run v1.22.21
Mar 01 13:07:17 parabol.example.com yarn[2364893]: $ pm2-runtime start pm2.config.js
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: Launching in no daemon mode
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Chronos:0] starting in -cluster mode-
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Web Server:1] starting in -cluster mode-
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Web Server:1] online
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Web Server:2] starting in -cluster mode-
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Chronos:0] online
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Embedder:3] starting in -cluster mode-
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Web Server:2] online
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [GQL Executor:4] starting in -cluster mode-
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [Embedder:3] online
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [GQL Executor:4] online
Mar 01 13:07:17 parabol.example.com yarn[2364912]: 2024-03-01T13:07:17: PM2 log: App [GQL Executor:5] starting in -cluster mode-
Mar 01 13:07:18 parabol.example.com yarn[2364912]: 2024-03-01T13:07:18: PM2 log: App [GQL Executor:5] online
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job autoPause: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job dailyPulse: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job weeklyPulse: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job batchEmails: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job scheduleJobs: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job updateTokens: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌱 Chronos Job processRecurrence: SKIPPED
Mar 01 13:07:19 parabol.example.com yarn[2364912]: 🌾🌾🌾 Server ID: 1. Ready for Chronos           🌾🌾🌾
Mar 01 13:07:23 parabol.example.com yarn[2364912]: embedder: run()
Mar 01 13:07:23 parabol.example.com yarn[2364912]: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Mar 01 13:07:23 parabol.example.com yarn[2364912]: Error: Invalid configuration: embedding_models is missing or not an array
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at ModelManager.isValidConfig (/opt/parabol/dist/embedder.js:704:13)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at new ModelManager (/opt/parabol/dist/embedder.js:734:10)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at getModelManager (/opt/parabol/dist/embedder.js:822:18)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at run (/opt/parabol/dist/embedder.js:13253:47)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at /opt/parabol/dist/embedder.js:13265:1
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at /opt/parabol/dist/embedder.js:13267:3
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at Object.<anonymous> (/opt/parabol/dist/embedder.js:13269:12)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
Mar 01 13:07:23 parabol.example.com yarn[2364912]:     at Module.load (node:internal/modules/cjs/loader:1207:32)
Mar 01 13:07:48 parabol.example.com yarn[2364912]: 🔥🔥🔥 Server ID: 2. Ready for Sockets: Port 3000 🔥🔥🔥
Mar 01 13:07:49 parabol.example.com yarn[2364912]: 🔥🔥🔥 Server ID: 3. Ready for Sockets: Port 3000 🔥🔥🔥
Mar 01 13:07:51 parabol.example.com yarn[2364912]: 💧💧💧 Server ID: 6. Ready for GraphQL Execution 💧💧💧
Mar 01 13:07:51 parabol.example.com yarn[2364912]: 💧💧💧 Server ID: 7. Ready for GraphQL Execution 💧💧💧
Mar 01 13:08:03 parabol.example.com yarn[2364912]: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Mar 01 13:08:03 parabol.example.com yarn[2364912]: Error: TIMEOUT
Mar 01 13:08:03 parabol.example.com yarn[2364912]:     at Timeout._onTimeout (/opt/parabol/dist/web.js:77444:16)
Mar 01 13:08:03 parabol.example.com yarn[2364912]:     at listOnTimeout (node:internal/timers:573:17)
Mar 01 13:08:03 parabol.example.com yarn[2364912]:     at process.processTimers (node:internal/timers:514:7)
Mar 01 13:08:05 parabol.example.com yarn[2364912]: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Mar 01 13:08:05 parabol.example.com yarn[2364912]: Error: TIMEOUT
Mar 01 13:08:05 parabol.example.com yarn[2364912]:     at Timeout._onTimeout (/opt/parabol/dist/web.js:77444:16)
Mar 01 13:08:05 parabol.example.com yarn[2364912]:     at listOnTimeout (node:internal/timers:573:17)
Mar 01 13:08:05 parabol.example.com yarn[2364912]:     at process.processTimers (node:internal/timers:514:7)
Mar 01 13:08:05 parabol.example.com yarn[2364912]: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```

**Comment by jordanh** [comment]
Hi @svenseeberg – curious if all is well? Do still need any help from us?

**Comment by svenseeberg** [comment]
Thanks for your feedback, it is very much appreciated.

Setting `AI_EMBEDDER_ENABLED` to `False` avoids the `Error: Invalid configuration: embedding_models is missing or not an array` message. However, the initial problem with the back end failing to store submitted reflections is not solved.

Now the server log only shows one error message. But AFAICT this is not directly caused by the error but an result due to the missing Sentry integration?

```
Mar 16 10:17:07 parabol.example.com yarn[243708]: Trace: SEND TO SENTRY DocumentID not found: s_vjkcLlbyo1Wqg8npi5T2PQ undefined undefined
Mar 16 10:17:07 parabol.example.com yarn[243708]:     at sendToSentry (/opt/parabol/dist/web.js:81601:11)
Mar 16 10:17:07 parabol.example.com yarn[243708]:     at subscribeGraphQL (/opt/parabol/dist/web.js:38207:30)
Mar 16 10:17:07 parabol.example.com yarn[243708]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 16 10:17:07 parabol.example.com yarn[243720]: Warning: uWS.HttpResponse writes must be made from within a corked callback. See documentation for uWS.HttpResponse.cork and consult the user manual.
Mar 16 10:17:13 parabol.example.com yarn[243708]: Trace: SEND TO SENTRY Missing Google Cloud Credentials in ENV undefined undefined
Mar 16 10:17:13 parabol.example.com yarn[243708]:     at sendToSentry (/opt/parabol/dist/web.js:81601:11)
Mar 16 10:17:13 parabol.example.com yarn[243708]:     at /opt/parabol/dist/web.js:729:34
Mar 16 10:17:13 parabol.example.com yarn[243708]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 16 10:17:13 parabol.example.com yarn[243708]:     at async /opt/parabol/dist/web.js:74561:22
Mar 16 10:20:39 parabol.example.com yarn[243708]: Trace: SEND TO SENTRY Missing Google Cloud Credentials in ENV undefined undefined
Mar 16 10:20:39 parabol.example.com yarn[243708]:     at sendToSentry (/opt/parabol/dist/web.js:81601:11)
Mar 16 10:20:39 parabol.example.com yarn[243708]:     at /opt/parabol/dist/web.js:729:34
Mar 16 10:20:39 parabol.example.com yarn[243708]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 16 10:20:39 parabol.example.com yarn[243708]:     at async /opt/parabol/dist/web.js:74561:22
```

More details of the browser console (Firefox Nightly):

![image](https://github.com/ParabolInc/parabol/assets/15197000/f4481998-68bf-47a5-8af4-ed149a758c90)

**Comment by Dschoordsch** [comment]
@svenseeberg missing Sentry is fine, the issue can be seen in this line:
```
DocumentID not found: s_vjkcLlbyo1Wqg8npi5T2PQ
```
That means the persisted GraphQL query with this ID was not found. This means something is wrong with your `preDeploy` step.

**Comment by Dschoordsch** [comment]
Or you could have cleared the `QueryMap` table from the old entries and the client is still not updated.

**Comment by svenseeberg** [comment]
> This means something is wrong with your `preDeploy` step.

```
$ node dist/preDeploy.js
🚀 Predeploy Started v7.22.1 sha:09302e65ce528987d4e61b48a5f903eb6f591d6d
👴 RethinkDB Migration Started
[migrate-rethinkdb] No new migrations
👴 RethinkDB Migration Complete
🐘 Postgres Migration Started
🔩 Postgres Extension Checks Started
   pgvector: skipping check (POSTGRES_USE_PGVECTOR !== true)
🔩 Postgres Extension Checks Completed
PostgreSQL - No migrations to run!
🐘 Postgres Migration Complete
🔗 QueryMap Persistence Started
⛓️ Prime Integrationgs Started
⛅️ Push to CDN Started
⛅️ Using Local File Store for client assets. Skipping...
⛅️ Server upload complete. Pushed 0 assets to CDN
⛅️ Push to CDN Complete
⛓️ Prime Integrations Complete
🔗 QueryMap Persistence Complete: 9 records added
🚀 Predeploy Complete
Done in 2.44s.
```
Looks good to me. Is there something I could miss w/o additional output?

> Or you could have cleared the `QueryMap` table from the old entries and the client is still not updated.

I'll have a look.

**Comment by svenseeberg** [comment]
I updated to `v7.22.4`. Then I got the following message:
```
Trace: SEND TO SENTRY Missing Google Cloud Credentials in ENV undefined undefined
```

After adding the following lines to the `.env` file, everything works again:
```
GOOGLE_CLOUD_PRIVATE_KEY_ID='foo'
GOOGLE_CLOUD_PRIVATE_KEY='foo'
GOOGLE_CLOUD_CLIENT_EMAIL='foo'
```

**Comment by Dschoordsch** [comment]
This step
> 🔗 QueryMap Persistence Complete: 9 records added
caches all queries used in the web app (js app that runs in the browser I called client). Only those will be served from the GraphQL executor (server). The id of those is referred to as `DocumentID` in the code.
If it can't be found, then there is a deployment issue, mismatch of web app and server, missing entries in the rethink database. I can only guess from here.

The google keys you've mentioned are used in this piece of code: https://github.com/ParabolInc/parabol/blob/master/packages/server/getGoogleLanguageManager.ts
It's used to auto-generate retro discussion group titles and get the sentiment of reflections. It could be made optional, but it wasn't high on the priority list yet. PRs are welcome. With missing env we should just return null and make the calls optional. For the group titles pick random words.

**Comment by svenseeberg** [comment]
> If it can't be found, then there is a deployment issue,

I'm not sure if my previous comment was clear enough on the issue: with version v7.22.4 the DocumentID error disappeared. That means at least in my case the original cause for this issue has been resolved (for now?).

**Comment by Dschoordsch** [comment]
In normal operation you should never run into this issue. One situation where this might occur: if you manually clear the persisted queries from the DB before updating the server version, then a browser still running the old app (because of service worker and cache) would use document ids not present on the server.

I'm happy it's working for you now. Are there any other issues, or can this be closed?
