### ISSUE TITLE
Embedder does not crash on error

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9643]
## Issue - Bug

- **How serious is the bug?** P2
- **OS:** macOS / Linux / Windows / ? Debian based Docker image on the tag v7.27.0
- **Browser:** Chrome / Safari / Lynx / ? -
- **Node version:** `node --version` v20.11.0
- **NPM version:** `npm --version` 10.2.4
- **RethinkDB version:** `rethinkdb --version` -

Logs on Staging for the Embedder:
```
{"time":"2024-04-14T09:00:26.737Z","level":"info","message":"ModelManager: creating Embeddings_ember_1 with 1024 dimensions []"}                                                                                   
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:                   
error: type "vector" does not exist                                                                                                                                                                                
    at Parser.parseErrorMessage (/home/node/parabol/dist/embedder.js:305675:98)                                                                                                                                    
    at Parser.handlePacket (/home/node/parabol/dist/embedder.js:305514:29)                                                                                                                                         
    at Parser.parse (/home/node/parabol/dist/embedder.js:305427:38)                                                                                                                                                
    at TLSSocket.<anonymous> (/home/node/parabol/dist/embedder.js:305210:42)                                                                                                                                       
    at TLSSocket.emit (node:events:518:28)                                                                                                                                                                         
    at TLSSocket.emit (node:domain:488:12)                                                                                                                                                                         
    at addChunk (node:internal/streams/readable:559:12)                                                                                                                                                            
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)                                                                                                                                         
    at Readable.push (node:internal/streams/readable:390:5)                                                                                                                                                        
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)                                                                                                                                             
    at PostgresConnection.executeQuery (/home/node/parabol/dist/embedder.js:358632:69)                                                                                                                             
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                                                  
    at async /home/node/parabol/dist/embedder.js:372860:28                                                                                                                                                         
    at async DefaultConnectionProvider.provideConnection (/home/node/parabol/dist/embedder.js:359165:20)                                                                                                           
    at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/embedder.js:372859:16)                                                                                                                     
    at async TextEmbeddingsInference.createTable (/home/node/parabol/dist/embedder.js:34764:5)                                                                                                                     
    at async Promise.all (index 0)                                                                                                                                                                                 
    at async run (/home/node/parabol/dist/embedder.js:35328:5)
```

Every Sunday EU morning Staging database gets restored and once that is done, the pre-deploy script is executed again, just in case.  The Embedder was running on Staging and when the database got wiped for the restoration the vector type didn't exist anymore for some time. Since then, the Embedder is there but would not exist. It just hangs there. The Embedder should have retried in some controlled way and then crash if it wasn't able to operate. 

Killing the Kubernetes pod makes it work right away:
```
{"time":"2024-04-15T09:15:49.070Z","level":"info","message":"ModelManager: creating Embeddings_ember_1 with 1024 dimensions []"}                                                                                   
{"time":"2024-04-15T09:15:49.189Z","level":"info","message":"Queueing EmbeddingsMetadata into EmbeddingsJobQueue for Embeddings_ember_1 []"}                                                                       
{"time":"2024-04-15T09:15:49.262Z","level":"info","message":"Importing discussion history up to now []"}                                                                                                           
{"time":"2024-04-15T09:15:51.672Z","level":"info","message":"Inserted 12923/16381 discussions in metadata ending at Wed Apr 10 2024 07:29:40 GMT+0000 (Coordinated Universal Time) []"}                            
{"time":"2024-04-15T09:15:53.441Z","level":"info","message":"Inserted 12948/16381 discussions in metadata ending at Thu Apr 04 2024 19:14:31 GMT+0000 (Coordinated Universal Time) []"}                            
{"time":"2024-04-15T09:15:55.348Z","level":"info","message":"Inserted 13351/16381 discussions in metadata ending at Fri Mar 29 2024 20:53:00 GMT+0000 (Coordinated Universal Time) []"}
```

That proves that the solution is what is proposed above: retry in a controlled way and crash after a while.

### Acceptance Criteria (optional)
The Embedder process crashes when there is an error that does not allow it to operate normally. Or at least it crashes after some retries.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by rafaelromcar-parabol** [comment]
@mattkrick this is related (if not the same) with what I shared with you yesterday. If you have already fixed it, just close the issue. If not, you could take it
