### ISSUE TITLE
Embedder syntax error at or near )

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9674]
## Issue - Bug

- **How serious is the bug?** P2
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`

The following error is shown on the [Embedder logs](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20kube_deployment%3Aparabol-embedder%20syntax%20&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2294410&storage=hot&stream_sort=desc&viz=stream&from_ts=1714118756011&to_ts=1714122356011&live=true) very often (54.7k times since it was deployed last Friday):
```
{"time":"2024-04-26T08:54:49.810Z","level":"error","message":"error: syntax error at or near \")\"\n    at Parser.parseErrorMessage (/home/node/parabol/dist/embedder.js:305703:98)\n    at Parser.handlePacket (/h
ome/node/parabol/dist/embedder.js:305542:29)\n    at Parser.parse (/home/node/parabol/dist/embedder.js:305455:38)\n    at TLSSocket.<anonymous> (/home/node/parabol/dist/embedder.js:305238:42)\n    at TLSSocket.e
mit (node:events:518:28)\n    at TLSSocket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at R
eadable.push (node:internal/streams/readable:390:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)\n    at PostgresConnection.executeQuery (/home/node/parabol/dist/embedder.js:358660:69)
\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/node/parabol/dist/embedder.js:372888:28\n    at async DefaultConnectionProvider.provideConnection (/home/no
de/parabol/dist/embedder.js:359193:20)\n    at async DefaultQueryExecutor.executeQuery (/home/node/parabol/dist/embedder.js:372887:16)\n    at async InsertQueryBuilder.execute (/home/node/parabol/dist/embedder.j
s:369037:24)\n    at async relatedDiscussionsStart (/home/node/parabol/dist/embedder.js:36591:19)\n    at async WorkflowOrchestrator.runStep (/home/node/parabol/dist/embedder.js:34513:16)\n    at async Embedding
sJobQueueStream.next (/home/node/parabol/dist/embedder.js:34363:7)\n    at async getNext (/home/node/parabol/dist/embedder.js:36062:22) {\n  name: 'JobQueueError',\n  retryDelay: undefined,\n  maxRetries: undefi
ned,\n  jobData: undefined\n} []"}
```

### Acceptance Criteria (optional)
The errors is not present anymore.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
fixed in v7.29
